### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by datsme** [mcedit/mcedit2#104]
I am trying to fix some problems on my server so I downloaded my server files and saved them to a single player game. The ssp loads fine and is playable however when I try to open the world with mcedit alpha 409, & 407 (haven't tried other versions) I get an error that says Unhandled Exception: 'RegionFile' Object has no attribute 'WriteChunk' and then it closes. It only happens with this world it opens my other worlds just fine. Any suggestions?

**Comment by codewarrior0** [comment]
One of your region files is damaged. The region repair in 2.0 is still under construction. If you want to use MCEdit 2.0, you'll have to open your world in 1.0 and save it first to repair the region file.

This will be fixed in the next build.
