### ISSUE TITLE
WindowsError: exception: access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by jajo-11** [mcedit/mcedit2#110]
Hi,
I tried to start alpha 435 on my Pc and got the Error seen above.

Here is the output of mcedit:
http://pastebin.com/RRkxfHz9

and the log file:
http://pastebin.com/UVagezpN

I am running Windows 10 build 10130 if it matters.

**Comment by codewarrior0** [comment]
Could you try build 450 or newer and post the log file for me?

**Comment by jajo-11** [comment]
Here you are: (Build 459)

Mcedit output:
http://pastebin.com/pgGG60vb

Log:
http://pastebin.com/cmBYJR4h

**Comment by codewarrior0** [comment]
All right, it looks like what these two issues have in common is the Intel graphics. 

In one report we have:
```
GL_VERSION: 2.1.0 - Build 8.15.10.2302
GL_VENDOR: Intel
GL_RENDERER: Intel(R) G45/G43 Express Chipset
```

And in the other:
```
GL_VERSION: 4.3.0 - Build 10.18.15.4204
GL_VENDOR: Intel
GL_RENDERER: Intel(R) HD Graphics 4400
```

I have a laptop with Intel HD Graphics 3000 but I can't reproduce the issue on it.

**Comment by codewarrior0** [comment]
This is what my laptop has:

```
GL_VERSION: 3.1.0 - Build 9.17.10.2843
GL_VENDOR: Intel
GL_RENDERER: Intel(R) HD Graphics 3000
```

**Comment by XXcreep387** [comment]
I had the same problem when I launched MCEdit for the secondX times

**Comment by codewarrior0** [comment]
Another log from @TH3REDSP1R1T: https://gist.github.com./anonymous/551092a1d70fd1ebe977#file-gistfile1-txt

This time, it's not an Intel driver.

```
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
 
Driver info:
GL_VERSION: 4.5.0 NVIDIA 353.06 (4, 5)
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 660/PCIe/SSE2
```

**Comment by codewarrior0** [comment]
Oh. I was under that impression because PyOpenGL will choose the available function out of several function names for the framebuffer functions, but it doesn't do the same thing for the multitexture functions.

**Comment by codewarrior0** [comment]
Possible fix in 0ae5213f40ef43a774a4a7bd9bca9cb2bc0ab7d5

**Comment by cydream25** [comment]
Just had the same error on alpha 560 on windows  64 bits.

**Comment by jajo-11** [comment]
The build 591 works for me. (or at least sometimes) I can't tell if it was fixed or it is the version of Windows I am running. I am now on Windows 10 build 10240.
Also: The menus are blurry for me if I have scaling on 125% wich is normally necessary on my computer to have reasonable sized text, so I disabled scaling for it and I am not only getting lesser crashes (wich I can't reproduce) but the text is larger and sharp!

**Comment by codewarrior0** [comment]
I enabled a PyOpenGL debug option that I had never used before, and found out the OpenGL context is disappearing mid-frame. I don't understand why. It disappears while MCEdit is running code that doesn't have anything to do with OpenGL.

**Comment by codewarrior0** [comment]
Disabling the garbage collector suppresses this error.

The OpenGL context seems to be lost when the QGLContext object is deallocated. It should not be deallocated since the QGLViewport object owns it. The fault is likely somewhere in PySide's wrapper management.

**Comment by codewarrior0** [comment]
No news in six months, assuming fixed.
