### ISSUE TITLE
Crash on opening modded world

### ISSUE THREAD

**Issue by tyronx** [mcedit/mcedit2#113]
Trying to open a world created by my own MC1.8 mod Vintagecraft, which creates worlds of WorldType VCDefault, trying to open it results in crash, using Alpha 459. Opening this world still worked in Alpha 370.

[WARNING][mcedit2.editorapp:88]:UserFilesDirectory: C:\Users\tyron\DOCUME~1\MINE
CR~1\MCEDIT~1.0AL\MCEdit User Data
[WARNING][mcedit2.widgets.configureblocksdialog:119]:Failed to read definitions
file defined_blocks.json
[ERROR][<string>:153]:Unhandled Exception:
        u'VCDefault' is not in list
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64
\build\build\mcedit2\out00-PYZ.pyz\mcedit2.panels.worldinfo", line 124, in revis
ionDidChange (self is a WorldInfoPanel)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64
\build\build\mcedit2\out00-PYZ.pyz\mcedit2.panels.worldinfo", line 86, in update
Panel (self is a WorldInfoPanel)
ValueError: u'VCDefault' is not in list

**Comment by Rubisk** [comment]
Thats on me.  Ill fix it to then

**Comment by tyronx** [comment]
Thanks a lot, is there any release with this fix in sight?

**Comment by codewarrior0** [comment]
Build 467 has the fix.
