### ISSUE TITLE
Failing at opening worlds.

### ISSUE THREAD

**Issue by Kryceris** [mcedit/mcedit2#114]
So I downloaded MCedit and tried to open my world. However when I opened my level.dat al i go is this: 
![afaf](https://cloud.githubusercontent.com/assets/12833209/8088456/21e7d012-0faa-11e5-8e93-bffc0dc5fec7.png)
I am using latest mac MCedit.

**Comment by Rubisk** [comment]
What type of world do you open? Does it load properly in vanilla Minecraft?

**Comment by Kryceris** [comment]
What do you mean with saying what type? It loads 100% properly in vanila Minecraft. It is command block contraption.

**Comment by Kryceris** [comment]
I think I know what you mean. Its superflat. Redstone ready.

**Comment by Rubisk** [comment]
Wait just a sec. This is the mcedit2 repository, and that's clearly MCEdit Unified. I can't move your issue, so please create a new one on that repo: https://github.com/Khroki/MCEdit-Unified
And close this one, to keep stuff organized, I'll help you out there.

**Comment by Kryceris** [comment]
Oh ok... I guess...
