### ISSUE TITLE
block searching is slow

### ISSUE THREAD

**Issue by supersnaketate** [mcedit/mcedit2#119]
mcedit 1.3.3.0
selecting the fill/replace tool or any tool that requires you to select a block type is very slow when searching, i believe this is because in this version of mcedit it is presenting every single possible block in the game, and im not just talking about solid blocks either, its displaying every orientation, every block state, every individual way for every block that could possibly be placed, it even has every single water height level flowing and non flowing

seeing as this is a major slowdown of working could we please have a a tickbox option to the selection box that lets us switch between "simplistic block types (water - flowing, water - still, sandstone stair, ect..)" and "all block types (water flowing level 1,2,3,4,5, ect.. sandstone stair(facing north, facing south, facing east, top facing south ect...)). 

i'll probably be using good old 0.1.8 from now on until a fix has been made

![xfgxf](https://cloud.githubusercontent.com/assets/12882314/8148677/5a739794-12da-11e5-91f7-76cc5895dccf.png)

**Comment by Rubisk** [comment]
1. This is an MCEdit 1.0 issue, please make sure to report in the right repository next time:
https://github.com/Khroki/MCEdit-Unified

LaChal did already fix it though, you can see the commit here. 
https://github.com/Khroki/MCEdit-Unified/commit/91186ffbe79b8fcab10c51bc2d2d797e6088cba2

**Comment by supersnaketate** [comment]
"This is an MCEdit 1.0 issue, please make sure to report in the right repository next time:"
sorry bout that, this site is confusing

"LaChal did already fix it though, you can see the commit here."
ok, but what do i do with that, im not a coder i dont know where to put that, and there is no blockpicker.py in the mcedit installation folder
