### ISSUE TITLE
MCEdit and World

### ISSUE THREAD

**Issue by AJLedbetter123** [mcedit/mcedit2#120]
Hi,

Just a quick one really, I'm trying to repair chuncks in my world so I open the level.day and it loads the world as normal, so I delete a chunck that's infected and create a new one, only problem is it doesn't create a new one with 'similar' blocks for example, if I delete water it replaces it with land, it didn't used to?

Any ideas how I could resolve?

It used to rebuild it and make it all 'fit in' if that makes sense?

**Comment by codewarrior0** [comment]
Sounds like you're using MCEdit 1.0, and that your world seed changed. All you can do is restore the seed from a backup.

**Comment by AJLedbetter123** [comment]
What shall I do to resolve? I don't understand what the 'seed' means?
