### ISSUE TITLE
Win10 dose not work

### ISSUE THREAD

**Issue by testsnake** [mcedit/mcedit2#123]
This dose not work with windows 10 prewview

**Comment by codewarrior0** [comment]
Need your MCEdit version number, your mcedit.log file, and a screenshot of the error message if any.

**Comment by testsnake** [comment]
I tried all of the versions available and it would not do anything once the setup opened

**Comment by testsnake** [comment]
Well, most of them

**Comment by codewarrior0** [comment]
Can't do anything without the required info from you.
