### ISSUE TITLE
"Pre-Anvil formats are not supported" error on launch

### ISSUE THREAD

**Issue by obee58** [mcedit/mcedit2#124]
http://gyazo.com/21a6cc1abe1d0b9f4d73be508d5c00a9

I have no idea how different this version of MCEdit is from the 1.4/1.5 days, I haven't used it in a year or so. I also was very bad at using it.

just wanted to use my note block studio schematic ;n;

**Comment by codewarrior0** [comment]
Fixed in ffa4c0a19a33e7abd844e9cedc141a55a1f05c7f

**Comment by codewarrior0** [comment]
Build 468 has the fix. If it still won't work, you can try one of the 1.0 versions instead.
