### ISSUE TITLE
removing mcedit2 from system

### ISSUE THREAD

**Issue by BigWicket** [mcedit/mcedit2#128]
Hi--my son downloaded mcedit2 onto his computer without reading the requirements or understanding how to set it up, and now his Minecraft is glitching and crashing. How can I safely remove/uninstall mcedit from his computer? It isn't showing up on the list of programs to uninstall. Thanks.

**Comment by codewarrior0** [comment]
There is no installer or uninstaller. All you have to do is delete the "mcedit2-win64-2.0.0alpha" folder that you unzipped.

**Comment by BigWicket** [comment]
Great--thanks!
