### ISSUE TITLE
Screen goes blank every time I right click to re-position a placed schematic

### ISSUE THREAD

**Issue by NuclearVideosHD** [mcedit/mcedit2#129]
i have a minecraft world that i am working on and i want to move my buildings. i copy them to move them but when i right click to drag them where i want, the screen goes blank and i cannot see anything. somone please help me, im very desperate as to how to fix this! Email me at nuclearvideoshd@gmail.com

**Comment by codewarrior0** [comment]
https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
