### ISSUE TITLE
Viris or Virus Threat?

### ISSUE THREAD

**Issue by DomSalinas** [mcedit/mcedit2#134]
I've recently tried to download mcedit and my antivirus says its a virus threat. Please help!

**Comment by codewarrior0** [comment]
https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md

**Comment by TrazLander** [comment]
If you're using Windows 10 and norton (or probably other virus softwares too) here's a response in another thread. https://github.com/Khroki/MCEdit-Unified/issues/425#issuecomment-118540345

> This will be fixed when norton supports windows 10, I usually use norton so MCEdit gets whitelisted when I compile, but since upgrading to win 10 norton no longer works and therefore MCEdit has no reputation information. Basically a false positive, for now just restoring the file and telling it to ignore it in the future is all you can really do.
