### ISSUE TITLE
Export Huge Schematic

### ISSUE THREAD

**Issue by jdscolam** [mcedit/mcedit2#135]
Hi,

I have a HUGE world (3000x3000 or so) that I want to export as a schematic so I can import it into another world.  MCEdit2 (64 bit version) has the great select all function, but it crashed when I try to export it.  Not even sure what would happen on an import.  Any ideas?

Thanks,

Jon

**Comment by codewarrior0** [comment]
https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md

**Comment by codewarrior0** [comment]
Try MCEdit 1.3.

**Comment by codewarrior0** [comment]
Also, if you want to import the entire world, just import the entire world directly. You can skip the export step.

**Comment by jdscolam** [comment]
Do you think it will handle huge world imports properly, and can I dictate where to import the world to?

**Comment by codewarrior0** [comment]
Adrian demonstrates it well enough in this video: https://www.youtube.com/watch?v=O_FVJiZcf30

**Comment by jdscolam** [comment]
As a follow up it worked in Chunk mode on 1.3, and took approximately 3 - 4 hours to save.  Thanks for the help!
