### ISSUE TITLE
no new compiled dev versions on download page

### ISSUE THREAD

**Issue by pokeball99** [mcedit/mcedit2#137]
http://www.mcedit.net/downloads.html
hasn't been one since https://github.com/mcedit/mcedit2/commits/987aa3e7c5e183ca032ad1c433cd0387e8bf460d

**Comment by codewarrior0** [comment]
Pity. I will have to see to getting the build server hosted.

**Comment by pokeball99** [comment]
@codewarrior0 its broken again,hasn't built for 16 days now, since
https://github.com/mcedit/mcedit2/commits/193ea92b600a47012c653b77c0cef62a2f2bb201

**Comment by codewarrior0** [comment]
Fixed now. Relevant issue is http://trac.buildbot.net/ticket/2936?cversion=0&cnum_hist=14
