### ISSUE TITLE
Unhanded Exception: Attempt to call an undefined alternate function (glActiveTexture, glActiveTextureABR), check for bool(glActiveTexture) before calling

### ISSUE THREAD

**Issue by storm345** [mcedit/mcedit2#138]
Same error as has been previously reported and closed as 'fixed' but I get it on 2.0.0alpha-540 (latest I think). I am using windows 8.1 with java 7 (64 bit) and my graphics card is a Nvidia Geforce GTX 770 (So the opengl version should definitely be high enough to run MCEdit)

Thanks for helping! :)

**Comment by codewarrior0** [comment]
Can you post your `mcedit.log`?
