### ISSUE TITLE
MCEdit does not work? Keeps stoping?

### ISSUE THREAD

**Issue by Svetaine** [mcedit/mcedit2#139]
Hello!

I have a problem with MCEdit :-1:  ... :(
Ewerytime i try to select a world, It stops! Even when I open one!

Could I cut a part of my generated world?
Could I speed up MCEdit?
Do I need a diffrent computer?
Did it fixed now, and I didn't updated my version?

I Don't know...
I need help! Please comment.

**Comment by codewarrior0** [comment]
https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
