### ISSUE TITLE
Explanation for NBT Tree

### ISSUE THREAD

**Issue by Rubisk** [mcedit/mcedit2#14]
AbsorptionAmount: Number of golden hearts * 2 left of your absorption effect
Air: Number of ticks left you can swim underwater without drowning.
DeathTime: Time since you died. Used for dying animations.
Dimension: End, Overworld, Nether.
Fire: Ticks left of being on fire. Standing in fire increases this number. Big negative values make you not turn on fire while standing in fire.
foodExhaustionLevel: Stuff you have done that causes your food to go down.
foodLevel: Number of drumsticks * 2
foodSaturationLevel: Number of hidden drumsticks
foodTickTimer: How long until food should tick.
HealF: Health since 1.6
Health: Health before 1.6
HurtByTimestamp: ???
HurtTime: Times since you've last been hit. Used for being invulnerable for half a sec after being hit.
Invulnerable: Whether or not you're invulnerable. Only affects mobs (?).
OnGround: If you're falling or not.
playerGameType: Kinda obvious?
PortalCooldown: How long until you can go through a portal again. Only affects mobs.
Score: Score to display on death screen.
SelectedItemSlot: Selected slot in hotbar -1
Sleeping: Whether or not you're in a bed.
SleepTimer: How long you've been in a bed.
XPLevel: Level of XP.
XPp: How full your xp bar is.
XpSeed: Unique ID to match you with your xp amount.
XPTotal: Number of XP points gathered.

Two useful links: http://minecraft.gamepedia.com/Chunk_format
http://minecraft.gamepedia.com/Player.dat_format

**Comment by codewarrior0** [comment]
Thanks for that. Frankly, there were only a couple I wasn't sure of. I was thinking about which ones should be shown up front beneath the player inventory and health and so on, which ones to hide under an "advanced" toggle, and which ones to only show via the NBT editor.
