### ISSUE TITLE
Vision bug on linux using wine.

### ISSUE THREAD

**Issue by campus735** [mcedit/mcedit2#143]
Description
I have had this problem before on sketchup but I haven't found any quide to fix it.
When I open world file "level.dat" and 3D rendering should start, then vision bugs.
Everything else are okay, it shows fps, coordinates, biomes and block type normally, but I have no vision.
What dlls there is needed for mcedit on windows? Is there linux/java version of mcedit?
I have installed vcrun2010 to 2013), direcrx9 10 and 11, secur32, atl90 and 100, vcomp90, and msvcm90 and 100

version: 2.0.0alpha-591
minecraft version: 1.8.7
OS: Linux ****** 4.1.3-1-ARCH #1 SMP PREEMPT Wed Jul 22 20:37:12 CEST 2015 x86_64 GNU/Linux
Error log:
http://pastebin.com/KdtUT8EY

Here's picture from my problem:
http://www.mediafire.com/view/ep3j2yafcac2hcp/Kuvakaappaus_2015-07-29_12-05-29.png

I think world file isn't needed because this is rendering bug.

**Comment by codewarrior0** [comment]
This line in your log file suggests you may not have much success running MCEdit using `wine`:

```
fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
```

Have you tried installing MCEdit from source using the directions in the readme?

**Comment by codewarrior0** [comment]
Since this happens also in Sketchup, I'm going to consider it a bug in wine.
