### ISSUE TITLE
The use of resource Packs doesn't seem to be working

### ISSUE THREAD

**Issue by tyronx** [mcedit/mcedit2#149]
Also when starting mcedit: 
(I selected vintagecraft as resourcepack)

[WARNING][mcedit2.editorapp:91]:UserFilesDirectory: C:\Users\tyron\DOCUME~1\MINE
CR~1\MCEDIT~4.0AL\MCEdit User Data
[WARNING][mcedit2.util.minecraftinstall:247]:Failed to load resource pack: IOErr
or(13, 'Permission denied')
Pack: vintagecraft
[WARNING][mcedit2.widgets.configureblocksdialog:119]:Failed to read definitions
file defined_blocks.json
[WARNING][mcedit2.util.minecraftinstall:247]:Failed to load resource pack: IOErr
or(13, 'Permission denied')
Pack: vintagecraft

**Comment by codewarrior0** [comment]
"Permission denied" is a problem on your end. Something else has exclusive access to the resource pack zip, probably an archiver tool like 7-zip.
