### ISSUE TITLE
MCedit 1.2.5.0 Win64 WONT START... 

### ISSUE THREAD

**Issue by Randomguy31** [mcedit/mcedit2#15]
When I run it, it opens cmd that obliges me to press enter, when I press enter, another cmd window opens and it closes.
when i open mcedit.exe :
![error1](https://cloud.githubusercontent.com/assets/10567910/5786188/a40f6806-9e13-11e4-9bcd-53ce641ff70e.png)

after pressing enter:
![error2](https://cloud.githubusercontent.com/assets/10567910/5786192/b5928194-9e13-11e4-9159-1ba83e26671f.png)

**Comment by DragonQuiz** [comment]
This issue tracker is for **MCEdit 2.0 only**. Issues with MCEdit 1.x need to be reported here: https://github.com/Khroki/MCEdit-Unified/issues Thanks
