### ISSUE TITLE
Automatic configuration of Blocks/Items

### ISSUE THREAD

**Issue by tyronx** [mcedit/mcedit2#150]
Shouldn't it be fairly easy to import modded blocks/items from an assets folder? Also it needs block ids? 
Since forge 1.7 block ids no longer can be assigned.

**Comment by codewarrior0** [comment]
Forge's block name<->blockID mapping is already imported. There is no other data provided by Forge; users are responsible for telling MCEdit what block models and textures to use for the Forge named blocks.
