### ISSUE TITLE
[Question] MCEdit with Command Line?

### ISSUE THREAD

**Issue by SirWilli** [mcedit/mcedit2#153]
hey,

is it possible to use mcedit via command line on ubuntu?

**Comment by codewarrior0** [comment]
Nope. GUI only.

**Comment by SirWilli** [comment]
@codewarrior0 hm, what is this then? https://github.com/mcedit/pymclevel

**Comment by Rubisk** [comment]
Note that this is the MCedit 2 repository. For questions about the original mcedit, head over to https://github.com/mcedit/mcedit. The original mcedit relied on pymclevel, which has a command-line interface, and can be found at https://github.com/mcedit/pymclevel.
