### ISSUE TITLE
MC Edit crashes upon loading a map

### ISSUE THREAD

**Issue by Poizony0** [mcedit/mcedit2#156]
Hello, My MC Edit crashes as soon as I click "Edit" after I select a map. The map renders fine on the screen above the edit button, not sure if that helps. Heres the error log: http://pastebin.com/chdZuv4L

How do I got about fixing this? Thanks!

**Comment by codewarrior0** [comment]
It looks like it's having a problem loading some of Minecraft's block model assets.

Try changing the Minecraft version and/or resource pack using the buttons on the top of the "choose world" screen.

**Comment by Poizony0** [comment]
I tried doing that and it still crashes. Is there a way to reset the default textures?

**Comment by codewarrior0** [comment]
You can use the default textures by choosing "(No Resource Pack)" in the resource pack menu.

Which Minecraft versions did you try?

**Comment by Poizony0** [comment]
I used the "No Resource Pack" setting, and im using MC 1.8.8

**Comment by codewarrior0** [comment]
Fixed
