### ISSUE TITLE
Issue: McEdit do not work for window 10

### ISSUE THREAD

**Issue by blaze78** [mcedit/mcedit2#157]
When I opened McEdit this happen

Here my Info:
Version: 2.0.0alpha-720

https://i.gyazo.com/f5b89275c55d39fe44f1717f556610df.png

Error Message: Obtained a GL context with this format:
Valid: True
Version: 1.1
Hardware Accelerated: False
Depth buffer: True, 32
Double buffer: True

Driver info:
GL_VERSION: 1.1.0 (1, 1)
GL_VENDOR: 'Microsoft Corporation'
GL_RENDERER: 'GDI Generic'

**Comment by codewarrior0** [comment]
Error log is incomplete.
