### ISSUE TITLE
WindowsError: exception: access violation in glActiveTexture

### ISSUE THREAD

**Issue by Bliversidge6** [mcedit/mcedit2#16]
![untitled](https://cloud.githubusercontent.com/assets/10571295/5788255/842921bc-9e22-11e4-8871-fc44f31642c5.png)

The first time I started this program this error message keep's showing, I removed and re-installed the program a few time but no change.

**Comment by codewarrior0** [comment]
Thanks.

The app needs to check the capabilities of your OpenGL driver on startup and give a more informative error message. If you can play Minecraft, you surely have a working glActiveTexture, so the actual bug is probably somewhere in PyOpenGL.

**Comment by codewarrior0** [comment]
Can you reproduce this error in build 417 or newer?

**Comment by xDeeKay** [comment]
I'm getting a similar error using version 2.0.0alpha-472 Windows 64-bit and 32-bit.
Here's the error, lemme know if you need any other info: http://pastebin.com/95Z0VF2M

**Comment by codewarrior0** [comment]
No news or duplicate reports in half a year
