### ISSUE TITLE
Minecraft: Windows 10 Edition

### ISSUE THREAD

**Issue by Captainkyle420** [mcedit/mcedit2#165]
MCedit doesnt work for windows 10 edition.... just get this blue blank sreen...
![image](https://cloud.githubusercontent.com/assets/15304010/10712947/decb29dc-7a66-11e5-8403-355fa9f7562f.png)

**Comment by codewarrior0** [comment]
*Windows 10 Edition* saves are the same as MCPE, which is not supported at this time.
