### ISSUE TITLE
i need help with tis bug for mcedit 2.0.0alpha-907 PLEASE HELP ME AS SOON AS YOU SEE THIS {BUG}

### ISSUE THREAD

**Issue by WolvesUnited** [mcedit/mcedit2#178]
HOW DO I MAKE THIS WORK YOU SAYED ITS FIXED DO I NEED TO RE DOWNLOAD MC EDIT mcedit 2.0.0alpha-907??

**Comment by WolvesUnited** [comment]
or not how do i do it

**Comment by codewarrior0** [comment]
I cannot help you.
