### ISSUE TITLE
mcedit 2.0.0alpha-907 please do not close 

### ISSUE THREAD

**Issue by WolvesUnited** [mcedit/mcedit2#179]
how cant you help me you made the dam software can you at lest give me some early accsess to the new build to beta test it i have a you tube channel to you can check that out to  at http://www.youtube.com/c/WolvesUnited/ PLEASE THINK ABOUT THIS LONG AND HARD THANKS YOURS  Justin Russell Quesnel @ WolvesUnited

**Comment by WolvesUnited** [comment]
send early accsess here justinquesnel2@gmail.com

**Comment by codewarrior0** [comment]
Rude. Please don't come back.

**Comment by WolvesUnited** [comment]
YOUR THE WORST MAN ALL I NEED IS A ANSWER AND I ASK THE QUESTION
