### ISSUE TITLE
Copy and paste not working (?)

### ISSUE THREAD

**Issue by GateTurtle** [mcedit/mcedit2#19]
Hi, I'm trying to copy and paste a simple selection from one world to another. At first when I copy it actually says it's copying but when I try to paste it nothing happens. (I'm using the last version "Tech Demo")

![copy](https://cloud.githubusercontent.com/assets/10764488/5967363/f4ec4ea2-a7ea-11e4-9c06-4d34e35b45b9.png)

Thanks for any help

**Comment by codewarrior0** [comment]
Only report startup failures in Tech Demo.
