### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by ftt6iruftftr57ftr7dtr7gtr7** [mcedit/mcedit2#191]
i cant use mcedijt 2 because i get this
![capture](https://cloud.githubusercontent.com/assets/16514860/12073691/6b5391d6-b0fa-11e5-9af0-a7aeab366acc.PNG)
 
here is my log: http://pastebin.com/sXNjMUnz 
(i tried the 64 and 32 bit version.)

**Comment by codewarrior0** [comment]
Did you have Minecraft open at the same time?

**Comment by ftt6iruftftr57ftr7dtr7gtr7** [comment]
no.

**Comment by codewarrior0** [comment]
Fixed
