### ISSUE TITLE
Starting up isuues

### ISSUE THREAD

**Issue by ZalgoFreak200** [mcedit/mcedit2#192]
Every time I try to start up mcedit I get this 
![screenshot 1](https://cloud.githubusercontent.com/assets/16522263/12077045/5269dc42-b191-11e5-92d9-04425f6b739c.png)

Here is my data: http://pastebin.com/TBKHxjGX
I tried both 32 bit and 64 bit
MC Version: 1.8.9 (no mods in use)
Windows Version: Windows 8.1 64-bit

**Comment by codewarrior0** [comment]
Fixed
