### ISSUE TITLE
MCEdit2 2.0.0alpha-919 won't open

### ISSUE THREAD

**Issue by Pigums** [mcedit/mcedit2#194]
So, I downloaded mcedit, everything was okay, imported a schematic, saved the world and closed the program. I then realized that I must of done something wrong cause my schematic wasn't showing up on mineways(another program). So I thought to redo it, thinking that I've missed a step in properly pasting a schematic into a world, till this error came up.

1st error:
http://pastebin.com/hf5UcGmD
Looks like this; http://i.imgur.com/Be9RykG.png

After I click continue, another error pops up with more info
http://pastebin.com/GSTuuhMz

And keeps on going, in an infinite loop. I tried quitting and re-opening, I've tried restarting it, I've also tried re-installing it. Nothing works.

How can I fix this?

Thanks

**Comment by codewarrior0** [comment]
Fixed in 3ad11dc0c7619ac067995c0896ef76d72ebbf0c0
