### ISSUE TITLE
Wrong 1.8 jar used as fallback when modded jars are present

### ISSUE THREAD

**Issue by dminer78** [mcedit/mcedit2#20]
I extract the file using 7zip and then loaded the exe which was given, I get a popup after a second with an error. Here's the link to the mcedit log: [http://pastebin.com/Ds2b7pjv](http://pastebin.com/Ds2b7pjv)

Running Windows 8.1 64-bit

**Comment by codewarrior0** [comment]
Could you get me a list of files under your `.minecraft\versions` folder?

A quick way to get it is to open a command prompt and run this command:

`tree /a /f c:\users\ben\appdata\roaming\.minecraft\versions > tree.txt && start tree.txt`

**Comment by dminer78** [comment]
Here's the entire list: [http://pastebin.com/KncDaTEw](http://pastebin.com/KncDaTEw)

**Comment by codewarrior0** [comment]
Great. Try moving all of the non-vanilla ones (at least, the non-vanilla 1.8 ones) out of the folder and run MCEdit again, let me know if it crashes.

**Comment by dminer78** [comment]
There we go! Just moved all the other jars out and it worked. Thanks!

**Comment by codewarrior0** [comment]
All right. I need to make it more picky about which 1.8 jar to fall back on. Leaving this issue open until it's fixed.

**Comment by OniOniOn-** [comment]
I thought people who posted issues here have advanced knowledge in computer programming, but actually most of the titles are named by codewarrior himself.
