### ISSUE TITLE
i may be doing something wrong here.

### ISSUE THREAD

**Issue by Kennet0508** [mcedit/mcedit2#203]
I extract the latest build, run it, then it crashes.

![tempslett](https://cloud.githubusercontent.com/assets/14075401/12341104/8ea3de1e-bb1f-11e5-971b-b9944d770537.png)

[INFO][<string>:168]:MCEdit2 version 2.0.0alpha-921 starting...
[INFO][acceleratesupport.py:13]:OpenGL_accelerate module loaded
[INFO][arraydatatype.py:275]:Using accelerated ArrayDatatype
[INFO][settings.py:100]:Loading app settings from C:\Users\KO-GAMER\Downloads\MC Edit\mcedit2-win32-2.0.0alpha-921\MCEdit 2 Files\mcedit2.ini
[INFO][loadablechunks.py:17]:Making checkerboard texture...
[INFO][minecraftinstall.py:246]:Checking install at C:\Users\KO-GAMER\AppData\Roaming\.minecraft
[INFO][minecraftinstall.py:253]:Found versions:
[u'1.8.9']
[INFO][minecraftinstall.py:246]:Checking install at C:\Users\KO-GAMER\AppData\Roaming\.minecraft
[INFO][minecraftinstall.py:253]:Found versions:
[u'1.8.9']
[WARNING][editorapp.py:91]:UserFilesDirectory: C:\Users\KO-GAMER\Downloads\MC Edit\mcedit2-win32-2.0.0alpha-921\MCEdit 2 Files
[INFO][editorapp.py:99]:Loaded translator.
[INFO][editorapp.py:108]:Loaded stylesheet.
[INFO][editorapp.py:120]:Loaded main window.
[INFO][editorapp.py:176]:Loaded panels.
[INFO][editorapp.py:219]:Loaded debug widgets.
[INFO][editorapp.py:269]:Loaded menus.
[INFO][worldlist.py:90]:Size hint: PySide.QtCore.QSize(120, 73)
[INFO][worldlist.py:91]:Size : PySide.QtCore.QSize(120, 100)
[INFO][worldlist.py:303]:Scanning C:\Users\KO-GAMER\AppData\Roaming\.minecraft\saves for worlds...
[INFO][qglcontext.py:53]:Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 361.43 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 970/PCIe/SSE2'

[INFO][worldview.py:888]:LAYER Blocks VISIBLE True
[INFO][worldview.py:888]:LAYER MonsterLocations VISIBLE False
[INFO][worldview.py:888]:LAYER Items VISIBLE True
[INFO][worldview.py:888]:LAYER TileEntities VISIBLE True
[INFO][worldview.py:888]:LAYER TileEntityLocations VISIBLE False
[INFO][worldview.py:888]:LAYER CommandBlockColors VISIBLE True
[INFO][worldview.py:888]:LAYER CommandBlockLocations VISIBLE False
[INFO][worldview.py:888]:LAYER ItemFrames VISIBLE True
[INFO][worldview.py:888]:LAYER TileTicks VISIBLE False
[INFO][worldview.py:888]:LAYER ChunkSections VISIBLE False
[INFO][worldview.py:888]:LAYER HeightMap VISIBLE False
[INFO][worldview.py:888]:LAYER Places Where Creepers Can Spawn VISIBLE False
[INFO][worldview.py:217]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\KO-GAMER\\AppData\\Roaming\\.minecraft\\saves\\Stronghold'))
[INFO][chunkloader.py:155]:Added: client MinimapWorldView(u'Stronghold: ')
[INFO][worldlist.py:358]:Centering on single-player player.
[INFO][worldlist.py:377]:Switched world view
[INFO][editorapp.py:279]:Loaded world list.
[INFO][editorapp.py:298]:Loaded status bar.
[INFO][editorapp.py:595]:Updating recent files menu: (0) []
[INFO][editorapp.py:305]:Loaded settings.
[WARNING][configure_blocks.py:121]:Failed to read definitions file defined_blocks.json
[INFO][editorapp.py:327]:Loaded app dialogs.
[INFO][editorapp.py:335]:Loading timer started
[INFO][editorapp.py:345]:Finding plugins
[WARNING][plugins.py:200]:Plugins dir C:\Users\KO-GAMER\Downloads\MC Edit\mcedit2-win32-2.0.0alpha-921\MCEdit 2 Files\plugins not found
[INFO][editorapp.py:362]:Opening worlds from command line.
[INFO][worldlist.py:390]:Removing view from WorldListWidget
[INFO][qglcontext.py:53]:Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 361.43 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 970/PCIe/SSE2'

[INFO][worldview.py:888]:LAYER Blocks VISIBLE True
[INFO][worldview.py:888]:LAYER MonsterLocations VISIBLE False
[INFO][worldview.py:888]:LAYER Items VISIBLE True
[INFO][worldview.py:888]:LAYER TileEntities VISIBLE True
[INFO][worldview.py:888]:LAYER TileEntityLocations VISIBLE False
[INFO][worldview.py:888]:LAYER CommandBlockColors VISIBLE True
[INFO][worldview.py:888]:LAYER CommandBlockLocations VISIBLE False
[INFO][worldview.py:888]:LAYER ItemFrames VISIBLE True
[INFO][worldview.py:888]:LAYER TileTicks VISIBLE False
[INFO][worldview.py:888]:LAYER ChunkSections VISIBLE False
[INFO][worldview.py:888]:LAYER HeightMap VISIBLE False
[INFO][worldview.py:888]:LAYER Places Where Creepers Can Spawn VISIBLE False
[INFO][worldview.py:217]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\KO-GAMER\\AppData\\Roaming\\.minecraft\\saves\\Stronghold'))
[INFO][chunkloader.py:155]:Added: client MinimapWorldView(u'Stronghold: ')
[INFO][worldlist.py:358]:Centering on single-player player.
[INFO][worldlist.py:377]:Switched world view
[INFO][worldeditor.py:420]:Scanning for regions in C:\Users\KO-GAMER\AppData\Roaming\.minecraft\saves\Stronghold...
[INFO][worldeditor.py:429]:Dim : Found 10384 chunks in 0.08 seconds.

**Comment by Kennet0508** [comment]
worked once i removed the world, from the saves folder. so it seems to be the world file if it gets loaded while the program is starting up, works fine when i run it and open the map after the program has started

**Comment by codewarrior0** [comment]
That's just a plain vanilla world? What's the latest version of Minecraft you played on it?

**Comment by codewarrior0** [comment]
Should be fixed by now.
