### ISSUE TITLE
Error: Float division by zero

### ISSUE THREAD

**Issue by Boefjim** [mcedit/mcedit2#206]
I'm trying to copy an area of my map, but sometimes when I copy it crashes giving an error like this:

![screenshot 1](https://cloud.githubusercontent.com/assets/16748131/12379870/c898ebdc-bd63-11e5-8822-8ce174c64066.png)

And then I click "OK" and then I need to restart it.
It either happens when I press "copy", but sometimes also when I press "paste"
But, sometimes, it doesn't crash at all, which seems a bit weird...

**Comment by codewarrior0** [comment]
This is a very old version of MCEdit 2. Try a newer one so you can post the full crash report.

**Comment by Boefjim** [comment]
Now it just instantly crashes...
This is the screen I get whenever I try to startup MCEdit 2.0.0 Alpha 921
![screenshot](https://cloud.githubusercontent.com/assets/16748131/12385830/4329ac40-bdc0-11e5-96be-f8c6719fdeb4.png)

**Comment by Boefjim** [comment]
Welp, it doesn't seem to happen anymore, so I guess this can be closed :P
