### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by ScullyV** [mcedit/mcedit2#211]
![untitled42](https://cloud.githubusercontent.com/assets/16855958/12532255/8bc2f9f4-c20f-11e5-9bd1-88b4e70361cc.png)

**Comment by ScullyV** [comment]
cant even open anything, just crashes! even after clicking restart MCEdit, or after clicking continue or closing the error, it just keeps popping up!! The only thing I can do is click quit MCEdit!!!!!!!!

**Comment by codewarrior0** [comment]
I can't click on your pastebin link.

**Comment by ScullyV** [comment]
no you cant, but it isnt that hard to write it or is it?
http://pastebin.com/V23pHAjR
copy that :)

**Comment by codewarrior0** [comment]
Duplicate of #110.
