### ISSUE TITLE
Downloads are 404

### ISSUE THREAD

**Issue by donotshake** [mcedit/mcedit2#217]
The 64bit and 32bit download of MCEdit directs to a 404

https://download.nodecdn.net/containers/mcedit/download/dev/mcedit2-win64-%7B%7Bdownload.rev%7D%7D.exe links to NodeCDN 404.

Unable to download MCEdit. It has been like this for a few days now.

**Comment by codewarrior0** [comment]
Works fine for me.  The `{{download.rev}}` means you don't have Javascript enabled.

**Comment by donotshake** [comment]
Thank you sir.
