### ISSUE TITLE
MC Edit startup Error

### ISSUE THREAD

**Issue by math227v** [mcedit/mcedit2#220]
Every time i try to start MCEdit up, there is comming the KeyError "Variants".
_-anonymous from Denmark
![mcedit error](https://cloud.githubusercontent.com/assets/18036461/13995809/1e3cfc86-f12b-11e5-9fec-1e8d342003e2.png)

**Comment by codewarrior0** [comment]
This is a very old version. Try one of the newer ones from http://www.mcedit.net/downloads.html

**Comment by math227v** [comment]
Ok Thanks


    _____________________________
