### ISSUE TITLE
AssertionError: Source checkout path cannot be represented as unicode.

### ISSUE THREAD

**Issue by trienow** [mcedit/mcedit2#223]
### System Info
Info | Version
------------ | -------------
Operating System | Windows 7 Professional SP1 64Bit
MCEdit | 2.0.0alpha-1006
Minecraft | 1.9
Python Version | 2.7.9

### How it happened.
1. I extracted it to `D:\Minecraft\MCEdit`
2. Put the contents of `mcedit2-win64-2.0.0alpha-1006` into `D:\Minecraft\MCEdit`
3. Ran `mcedit2.exe`
4. Console Opened.
5. Console closed and the MCEdit process was gone.

### .log files
- The `mcedit.log` file is empty.
- The log, when executing `mcedit2.exe` via the command-line: https://gist.github.com/trienow/7a10dbafc7782f77b27b013276699799

### Other Notes
- Versions prior to `2.0.0alpha-1006` work fine. I tested back to `2.0.0alpha-992`
- Running it in it's extracted folder (`mcedit2-win64-2.0.0alpha-1006`) has no different effect.

**Comment by turbolego** [comment]
I have the same error.
mcedit2-win64-2.0.0alpha-1006
Windows 8.1
Python 2.7.11
Minecraft 1.8.9

![mcedit1006 fail](https://cloud.githubusercontent.com/assets/2650749/14159311/8099e16e-f6d5-11e5-92ff-7dfa06ec65b7.png)

**Comment by codewarrior0** [comment]
Fixed in e4bb8eed984e0e88488dff2fd60472774e21dfe0
