### ISSUE TITLE
MCInstallError: Minecraft versions folder does not exist.

### ISSUE THREAD

**Issue by SoupRGyro** [mcedit/mcedit2#23]
Upon extraction on PC version, mcedit2.exe (both in the main Minecraft directory and in the .minecraft directory both give a version error and fail to run.  mcedit.log file is generated with a lot of missing files that all use the same directory structure as the example below.  How can we configure to use appropriate install folders?

"c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.pyz\mcedit2.util.minecraftinstall"

**Comment by codewarrior0** [comment]
Post your mcedit.log to [pastebin](http://pastebin.com/) and link it here.

**Comment by codewarrior0** [comment]
This might be the same issue as #20. Try removing your modded versions from `.minecraft/versions`

**Comment by SoupRGyro** [comment]
Removed all modded versions as instructed.  Same error.  I am running Win7-64bit and trying to run mcedit2.exe from my .minecraft directory.

http://pastebin.com/5vD3GDEU

**Comment by codewarrior0** [comment]
Okay. If it can't find the versions folder, it is supposed to prompt you for one. I'll have to figure out why it doesn't.

**Comment by codewarrior0** [comment]
Fixed for next release.
