### ISSUE TITLE
MCEdit does not completely load the contents of my world

### ISSUE THREAD

**Issue by Silevern** [mcedit/mcedit2#231]
Currently using MCEdit 2.0.0alpha-1018

I'm currently making the [front garden of the Oheka Castle](https://www.google.com/maps/uv?hl=en&pb=!1s0x89e829ced9dd863f%3A0x52d228970708615f!2m5!2m2!1i80!2i80!3m1!2i100!3m1!7e115!4shttps%3A%2F%2Fpicasaweb.google.com%2Flh%2Fsredir%3Funame%3D104175960857574603553%26id%3D6185544407412674946%26target%3DPHOTO!5soheka%20castle%20-%20Google%20Search&imagekey=!1e3!2s-afMd1m5u1yo%2FVvrDINkbofI%2FAAAAAAAAQYU%2FMYDCzLw3IoYjxAwbtYcwrlxXnPoU3nyog&sa=X&ved=0ahUKEwimkcyvkOzMAhVClB4KHdDjCY8QoioIhgEwDg) and I've almost completely finished. I've decided to use MCEdit to clone a portion of my garden because making enormous pools of water manually sucks. I also would like to use the clone tool to make the long walkaway that wraps around.

However, when I load up, the entire center of the garden does not load. The bare edges do show up but everything within does not load. [Screenshot here](http://imgur.com/sh7MgI2).

Should I try using a different alpha version, or try using MCEdit 1.0, or is this some kind of error that I can't solve?

Thanks,
Silevern

**Comment by codewarrior0** [comment]
This is a rendering error. The details will be in the `mcedit.log` file in the `MCEdit User Data` folder next to the application.

**Comment by codewarrior0** [comment]
No new information for 3 months.
