### ISSUE TITLE
Mc edit filter:create shop error.

### ISSUE THREAD

**Issue by Swaggydogy** [mcedit/mcedit2#234]
hi! my name is billydog132 in minecraft and i want to talk about a big problems in the mc edit filter (Create shops), before it's working but now nothing...
I am on mac (version:10.10.5) and i use Mcedit (version:1.5.3.0) in minecraft 1.9.3.
So when i use the MCedit filter: Create Shops, the chest is good and i double click into the chest.
I make a farmer personal villager named "Jean" and it make this error:
![capture d ecran 2016-05-28 a 21 47 58](https://cloud.githubusercontent.com/assets/19621748/15632393/0ed3bae8-2590-11e6-8ebc-fd17adf39882.png)

Please help me!
make this never happened again...

**Comment by codewarrior0** [comment]
Report this issue here: https://github.com/Khroki/MCEdit-Unified/issues

**Comment by Swaggydogy** [comment]
if i do this my issue will be not closed?

**Comment by robske110** [comment]
Yes
