### ISSUE TITLE
certain world will not load past 28% - crashes mcedit2

### ISSUE THREAD

**Issue by arliben** [mcedit/mcedit2#236]
http://pastebin.com/hG1EJTX2

Windows 7 - 64 bit
Minecraft 1.10

If I select the world and wait a second or double click on it to edit I get the same error. if I've double clicked it stops at 28%
I hope this is everything you need, apologies if I missed something.
At one point in time this world was editable, I didn't open it and minecraft at the same time or anything. It is however a copy of a save, but like I said - it used to work.

**Comment by codewarrior0** [comment]
> apologies if I missed something.

From the reporting guidelines:

> * **MCEdit Version Number** - Found in the title bar of the main window.

**Comment by arliben** [comment]
MCEdit 2.0.0alpha-907

**Comment by codewarrior0** [comment]
That version is seven months old. Go to http://www.mcedit.net/downloads.html to download a newer version.
