### ISSUE TITLE
mcedit won't even start, crashes on start

### ISSUE THREAD

**Issue by Dan9999** [mcedit/mcedit2#237]
When I start the application, it immediately crashes with the error: "AttributeError: 'ModelPlayer' object has no attribute 'modelTexture'"

Log: http://pastebin.com/tz8FUAyf
All I do to get the error is when I start the application
Windows 7 64 bit
Minecraft 1.9.4
MCedit2 alpha-1068

I did not change any files in the install folder, only started the application straight from the folder

**Comment by codewarrior0** [comment]
Fixed
