### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by XmarcoX00** [mcedit/mcedit2#242]
I recive this issue when i exit from the Blocks/items configurator
http://pastebin.com/1aKvYdtu

and if possible I would like to know how "to add mod" to mcedit
thanks, XmarcoX00

**Comment by codewarrior0** [comment]
Fixed.

No way to directly "add a mod" to MCEdit - the configurator is the only way for now.

**Comment by XmarcoX00** [comment]
Thanks
