### ISSUE TITLE
please make mc edit mac compatible

### ISSUE THREAD

**Issue by PRIVATEPONY** [mcedit/mcedit2#244]
im done with this crap of me not being able to use software because its not on mac i want to use so many different programs but cant because of this bullcrap . I hae wanted to use programs like source filmaker and games and games and games and mc edit for a long time and want the supposed mac versions but if only they werent viruses so fix this

**Comment by codewarrior0** [comment]
ok

http://www.mcedit.net/downloads.html

**Comment by PRIVATEPONY** [comment]
thank you so much! (:
