### ISSUE TITLE
Suggestion: Increase MAX view distance to 100 or more

### ISSUE THREAD

**Issue by wolveseyes101** [mcedit/mcedit2#245]
I know its for problems but i didnt see a suggestion option on your web page i would very much like the max view past 24 something as high as 100 or even give a option to set your own from 1-999 like in the options of my current version i can control ram usage atleast i think thats what the max MB is, and i can control the hieght at which the world loads without details instead of 200 something i put it at 500 would like that option for the Max view for extreme screenshotting, and extreme map editing, and just seeing my entire map in general,,,, because of how big my map is i can only see a city at a time and im trying to edit between multiple locations and it all cant stay loaded when its max is only 24, please and thank you! and im sure others would love this option to i understand not everyone has the ram for it but technology gets better everyday and being able to control the max you can test the limits of your pc and find out how far you can go before it crashes and then avoid that, but for others who can go further or in a year or two when ram and technology doubles again we have that option to increase the distance as we upgrade.

**Comment by codewarrior0** [comment]
Done.
