### ISSUE TITLE
Error ~ Please Help

### ISSUE THREAD

**Issue by tyschnoor** [mcedit/mcedit2#246]
when i try to load a world this shows up

> An error occurred while opening C:\Users\Dawn\Desktop\New folder\MCEdit 2 Files\schematics\apartment building.schematic
> 'SchematicFileAdapter' object has no attribute 'requireRevisions'
> 
> Traceback
> (most recent call last):
> File "mcedit2\editorapp.py", line 699, in loadFile (self is a MCEditApp)
> File "mcedit2\editorsession.py", line 183, in init (self is a EditorSession)
> File "mceditlib\worldeditor.py", line 271, in requireRevisions (self is a WorldEditor)
> AttributeError: 'SchematicFileAdapter' object has no attribute 'requireRevisions'

**Comment by codewarrior0** [comment]
Schematics cannot yet be edited directly.
