### ISSUE TITLE
Problem : it don't load my schematic

### ISSUE THREAD

**Issue by Quef64** [mcedit/mcedit2#249]
Hello,
I have a problem with my big schematic (855x699), it don't appear on my minecraft world when I save it on McEdit.
I'm on Windows 10 32-bit,  I use mcedit2-win32-2.0.0aplpha-1071 and I play on minecraft 1.8.7.

Could you fix that problem, please?
Thanks.

**Comment by codewarrior0** [comment]
From the guidelines:

> Steps to Reproduce - Step by step, tell us exactly which buttons to click on, text to enter, and keys to press that lead you to discover the problem.

From your brief description, I can only infer that you tried to MCEdit your world while at the same time playing it in Minecraft, and expected the building to appear instantly in-game.

You cannot open a world in both MCEdit and Minecraft at the same time.

**Comment by aidangreen2** [comment]
codewarrior I have the same problem

**Comment by codewarrior0** [comment]
Assuming user error.

Will reinstate the startup warning that tells you not to open the same world at the same time in both Minecraft and MCEdit.
