### ISSUE TITLE
KeyError: (u'Resource %s not found in search path', u'assets/minecraft/models/block/cube_all.json')

### ISSUE THREAD

**Issue by BluetheFox** [mcedit/mcedit2#25]
i got it from the website and it just crashes saying that it cant find cube_all.json.

Steps to Reproduce - 
1. download it from the mcedit website
2. extract it to a folder (possible on external HDD)
3. run the mcedit2.exe
4. it crashes immediately after the window first opens
MCEdit Version Number - 2.0.0-alpha1-win-amd64
Minecraft Version Number - 1.8.1
Operating System Version - Windows 7

Error log - http://pastebin.com/HV56DPYS

**Comment by codewarrior0** [comment]
This is surely the same issue as #20. Try removing modded versions from your `.minecraft/versions` folder.

**Comment by BluetheFox** [comment]
I did now, but it still does the same thing.

**Comment by codewarrior0** [comment]
Can you do me a favor, and try to find out which MC version makes it crash when you put it into the .minecraft/versions folder?

**Comment by BluetheFox** [comment]
sorry, no cause im pretty busy as of late with trying to fix problems with
my comp. and i ended up deleting those other versions. :/ if i could help i
would

**Comment by ComputerCandy** [comment]
The version that Crashed me is b1.8.1

**Comment by ComputerCandy** [comment]
![screenshot 2015-02-28 11 30 47](https://cloud.githubusercontent.com/assets/11236933/6422422/4f581132-bf3d-11e4-88ec-4f868a90e504.png)
My Version List

**Comment by OniOniOn-** [comment]
Why does your github have better font?

**Comment by codewarrior0** [comment]
Looks like his Cleartype is set to strong hinting.

Anyway, this issue will be fixed in the next release.
