### ISSUE TITLE
Mouse Wheel Zoom Doesn't Work in Overhead World View

### ISSUE THREAD

**Issue by cjunekim** [mcedit/mcedit2#252]
With the overhead world view selected, the mouse wheel zoom in/out does not show any effect at all.

However, mouse wheel works all right in the 2D(cutaway) view.

Using IPython console I could also manually adjust the zoom scale with:

`editorapp.MCEditApp.app.sessions[0].editorTab.overheadViewFrame.worldView.scale=0.1`

OS : MS Windows 10 Pro
MCEdit : 2.0.0alpha-1071
MC : 1.8, 1.9, 1.10

**Comment by codewarrior0** [comment]
Fixed.

>Using IPython console I could also manually adjust the zoom scale

Nice!
