### ISSUE TITLE
Error when exporting a selection

### ISSUE THREAD

**Issue by retfarcimak** [mcedit/mcedit2#255]
Hi. Sorry if there are spacing breaks- I typed this up with notepad.

Anyway, I had a problem when trying to copy something from one world into another world. I pasted the log at the bottom, before special info. The special info is a mod version I was using. If the mod is what's causing it, please let me know.

Steps:

Open world
Select area
Export area

Version:

MCEdit 2.0.0alpha-1071

MC version:

MC 1.7.10

OS:

Windows 8 32 bit

Error log:

MCEdit version: 2.0.0alpha-1071
Python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.2
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.2.0 - Build 10.18.10.3282 (4, 2)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 4400'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editorsession.py", line 946, in export (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 870, in exportSchematicIter (self is a WorldEditorDimension)
  File "mceditlib\schematic.py", line 46, in createSchematic  
  File "mceditlib\schematic.py", line 213, in __init__ (self is a SchematicFileAdapter)
ValueError: negative dimensions are not allowed

Mod:

Pixelmon

Mod version:

Pixelmon 3.5.1

MC version/world version:

MC 1.7.10

**Comment by codewarrior0** [comment]
Can't reproduce. Assuming this is fixed since build 1071.

I'm certain your mods have nothing to do with it.

**Comment by retfarcimak** [comment]
Ok. Thank you.
