### ISSUE TITLE
Schematics Not Loading

### ISSUE THREAD

**Issue by aidangreen2** [mcedit/mcedit2#258]
Hello! I recently downloaded MCedit to load a schematic in my world since there was no world download. I download the schematic file, put it in the MCEdit schematics folder, then opened the exe file. I clicked "Import", then "Import", then located the MCEdit folder to open the schematic folder. I was able to move the schematic around as normal, it even loaded in properly! But, I clicked save (which then a green check appeared), clicked "Save world as" under MCEdit (nothing happened). Under the same tab, I clicked save (nothing happened either). Then, assuming everything was OK, under MCEdit, I clicked "Exit". Once I loaded up the world, the schematic was not there. Please help!

Windows 10 64-bit
HP laptop (pavilion I believe) 
Minecraft Forge 1.8, using WorldEdit and ReplayMod.

**Comment by codewarrior0** [comment]
Can't reproduce. Are you sure you didn't try to edit the world while playing it in Minecraft at the same time?

**Comment by aidangreen2** [comment]
Yes, the world was not open simultaneously. Am I pasting a schematic in correctly?

**Comment by codewarrior0** [comment]
My hunch is you didn't press "Confirm" between positioning the import and clicking "Save". It's supposed to confirm the import automatically when you save, but maybe that part is broken.

**Comment by aidangreen2** [comment]
Ok, I did everything the same, except that I pressed CONFIRM after placing the schematic. @codewarrior0 but when I loaded up the actual world after clickinig MCedit > Exit mcedit, then the world immediately crashed upon entering. I also have mods installed. (replay mod & worldedit)

**Comment by aidangreen2** [comment]
I tried loading it up with a non-modded client, (world loaded successfully!), but the schematic got all screwed up. @codewarrior0

**Comment by codewarrior0** [comment]
> the world immediately crashed
> the schematic got all screwed up

Not going to badger you for details.

**Comment by aidangreen2** [comment]
??? which details, I might make another issue recording myself performing the action
