### ISSUE TITLE
MCEdit 2 - Failed to download the required Minecraft Version

### ISSUE THREAD

**Issue by EzequielDM** [mcedit/mcedit2#259]
**Error log** - http://pastebin.com/4G2RvC3G

**Steps to Reproduce** - No steps, I just extracted it using the Self-Extractor and opened the EXE and it gives me the error.

**MCEdit Version Number** - MCEdit 2.0.0-beta2.
**Minecraft Version Number** - 1.7.10 (No Mods)
**Operating System Version**: Windows 8.1 Pro - x64 Bits

**Comment by codewarrior0** [comment]
That's not an error. It gives you a "Retry" option and another option to manually point it to your Minecraft versions.

**Comment by EzequielDM** [comment]
Thx codewarrior0

**Comment by zero319** [comment]
I have the same problem, I don't know how to fix it

**Comment by tankcr** [comment]
I have tried pointing it to my .minecraft folder and it fails saying it needs a version at least 1.9 or higher, and I have 1.10.2 installed?

**Comment by Anora** [comment]
same problem here and I have it pointing to my 1.11.2 install

**Comment by ShalRaj** [comment]
was anyone able to fix this error....

**Comment by thundR** [comment]
What a lazy reply, this is an error.

**Comment by naqaden** [comment]
For not being an error, it mentions "error" a lot. There is even a spelling error in the description ;)

QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function **ERR_get_error**

Failed to download the required Minecraft version.
**An error occured** while downloading Minecraft from the official servers.
Failed to download version manifest. (**Error code**: PySide.QtNetwork.QNetworkReply.**NetworkError**.**UnknownNetworkError**)

**Comment by Ozitec** [comment]
I found out how if you are using a snapshot, I changed it to the newest version 1.12.2
.

**Comment by p0lar-bear** [comment]
What I don't understand is why this is happening?

The source says it's trying to fetch https://launchermeta.mojang.com/mc/game/version_manifest.json, and that loads up in my browser just fine. Is there something wrong with the Qt library that it's failing?

**Comment by EzequielDM** [comment]
> What I don't understand is why this is happening?
> 
> The source says it's trying to fetch https://launchermeta.mojang.com/mc/game/version_manifest.json, and that loads up in my browser just fine. Is there something wrong with the Qt library that it's failing?

You must be joking you're necroing a closed issue from 4 years ago
