### ISSUE TITLE
Issues with non-standard Minecraft install

### ISSUE THREAD

**Issue by LiruJ** [mcedit/mcedit2#26]
I have Minecraft on my HDD (D:) and MCedit in its own folder in the Minecraft folder, when I start it up it gives the error:

[Error 3] The system cannot find the path specified: u'C:\\Users\\Liru\\AppData\\Roaming\\.minecraft\\resourcepacks\\*.*'

I've tried changing the .ini file, but it resets every time I start it up.

**Comment by codewarrior0** [comment]
This is fixed in the next release. It will prompt you for Minecraft installs if it can't find any.
