### ISSUE TITLE
Windows wont open mcedit.

### ISSUE THREAD

**Issue by Trix110** [mcedit/mcedit2#260]
Basically, windows thinks that mcedit is a threat and won't let me open it.

**Comment by robske110** [comment]
follow these steps:
-Fuck microsoft
-Disable smart screen filter(s)
-Disable Windoof defender's real time protection
-Disable any other anti virus software
-If you still can't open it post some more information here and close this issue
-If you can open it close this issue

please replace windoof with windows

**Comment by thebigsmileXD** [comment]
@robske110 or use brain, search previous issues and see the solution: a beta version of MCEdit with opengl support on windows 10.

**Comment by robske110** [comment]
Well, he says that soem antimalware kicked off.

**Comment by thebigsmileXD** [comment]
Damn it, should read more carefully. Anything else happens when you right-click and open as administrator?

**Comment by codewarrior0** [comment]
Add an exception for MCEdit in your antivirus or Windows Defender settings.
