### ISSUE TITLE
Crashes while opening non-modded world

### ISSUE THREAD

**Issue by Stuart2202** [mcedit/mcedit2#261]
I make animations so i use MCEdit to build things often but now when i try to open a world **it whitescreens before crashing.**
When i first upgraded from MCE 1.7 to 2.00 it would do this every so often but when i reopend it it worked fine but now it does it all the time. 
Edit: now when i open MCE this happens http://pastebin.com/ba7ZDDwv

P.S im new to git hub so if i make a mistake tell me

**Comment by Stuart2202** [comment]
h

**Comment by codewarrior0** [comment]
> Edit: now when i open MCE this happens http://pastebin.com/ba7ZDDwv

This is fixed in beta3.

**Comment by Stuart2202** [comment]
I forgot to remove that
