### ISSUE TITLE
[QUESTION] Can use it?

### ISSUE THREAD

**Issue by nathan130200** [mcedit/mcedit2#262]
I can use MCEdit in 1.9 > versions?

**Comment by Stuart2202** [comment]
yes

**Comment by aidangreen2** [comment]
stuart are you a dev

**Comment by Stuart2202** [comment]
no but ik this from my exp

**Comment by aidangreen2** [comment]
stuart my schematics aren't loading, I posted an issue on it. I'm in need of desperate help

**Comment by Stuart2202** [comment]
im not a mod but alot of people are having this problem and it should be fixed soon

**Comment by codewarrior0** [comment]
> I can use MCEdit in 1.9 > versions?

Yes. Newer blocks will be purple and may not have the correct lighting after editing them.

**Comment by nathan130200** [comment]
It is true the blocks of 1.9 were all buggy. Ah MCEdit 2 contains some bugs that when I edit and save the map he or saved. I had to download the MCEdit 1 if not I would not have been able to import / export schematics.
