### ISSUE TITLE
MCEdit 2 - Crashes when try to edit map!

### ISSUE THREAD

**Issue by EzequielDM** [mcedit/mcedit2#263]
When I try to edit the map, I open, select the map and when I click Edit, it says that MCEdit2 isnt responding.

Version: Latest 2.0.0beta
OS: Windows 8.1 Pro 64-Bits
Mods&Version: 1.7.10 (Optifine)

**Comment by Stuart2202** [comment]
i have the same problem but with no mods
https://github.com/mcedit/mcedit2/issues/261

**Comment by codewarrior0** [comment]
> MCEdit2 isnt responding.

This isn't a crash. Wait for it to continue or crash, and then post the crash details.
