### ISSUE TITLE
Wrong center of brush (rtfd-testing version)

### ISSUE THREAD

**Issue by acterhd** [mcedit/mcedit2#270]
I compared my new fix and official solution. I can say, that official not fix cursor center of brush. In my fix I long time worked with center of brush cursor. Try fix again. 

Under cursor center I means not only hover, but center in edges (crossing-cubes). 

Step to reproduce: 
- Enable 2x2 brush
- Hover between blocks, and move cursor.

**Comment by codewarrior0** [comment]
Do you remember badmouthing me and my project, in Russian? I do.

**Comment by acterhd** [comment]
Прошу простить меня, беру свои слова обратно...
