### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Wingman223** [mcedit/mcedit2#273]
Error log:
http://pastebin.com/RHa0FvWG

Steps to reproduce:
When trying to open a minecraft 1.7.2 modded world from "Feed the beast - Sky factory 2.5" mcedit runs into the error : "'NoneType" object is not iterable."

Here is the world file to test
https://drive.google.com/open?id=0B-vBSbm3fMKCeFZfWlNiYmx4TTg

MC Edit Version Number : 2.0.0-beta4
Minecraft Version : 1.7.2 modded
Operating System: Windows 10

**Comment by codewarrior0** [comment]
Fixed
