### ISSUE TITLE
cannot save 

### ISSUE THREAD

**Issue by davesaint88** [mcedit/mcedit2#274]
MCEdit 2.0.0-beta64
minecraft 1.6.61, no mods
win 10 home 64bit

There is a small green check mark on the save icon, and now my save button is locked. I cannot save.
![green](https://cloud.githubusercontent.com/assets/22383150/18770623/13ec65bc-8106-11e6-854a-31a249e0ff19.jpg)

**Comment by codewarrior0** [comment]
Working as intended. There are no changes to save.

**Comment by davesaint88** [comment]
No. It isn't. That check mark wasn't there 2 days ago. If i move anything
and try to save, its not possible.
