### ISSUE TITLE
MCPE Compatability

### ISSUE THREAD

**Issue by AwesomeRedstoner** [mcedit/mcedit2#275]
Is MCEDIT 2.0 or any other 2.0 version compatable with MCPE?

I tried to load a world onto it via copying the 'level.dat' of my MCPE world, but instead of actually loading the world, MCEDIT presents me with a void world with nothing in it.

If MCEDIT 2.0 or other versions of MCEDIT 2.0 are not compatible with MCPE yet, please let me know, and all will be fine. if not, please solve the problem!

P.S. If you need more details, feel free to ask.

BTW, all versions of MCPE and MCEDIT 2.0 at to be the latest version on the 29/9/16

**Comment by codewarrior0** [comment]
No.
