### ISSUE TITLE
KeyError: u'Key UUIDLeast not found.'

### ISSUE THREAD

**Issue by Typhome** [mcedit/mcedit2#276]
Error log
http://pastebin.com/1VmVdwJw

1. Open MCEdit 2.0.0-beta5 (I tried both 32-bit and 64-bit, still happens)
2. Load world (1.10.2)
3. Import schematic (about 4.6MB file size)
4. Set schematic location (coords)
5. Confirm
6. Bam error... (after "Writing modified chunks 99%")

MCEdit 2.0.0-beta5
Minecraft 1.10.2

Windows 10 Pro 64-bit

**Comment by codewarrior0** [comment]
Fixed
