### ISSUE TITLE
MCEdit Crashes when loading a world

### ISSUE THREAD

**Issue by nsmoller** [mcedit/mcedit2#279]
Just installed this on my macbook.  trying to edit a world and it opens, and as soon as the UI is loaded the app crashes.

http://pastebin.com/pMJXs8sj

**Comment by codewarrior0** [comment]
Probably a duplicate of #228, but since the log contains no Python traceback, we may never know.

**Comment by justinsandhu** [comment]
I also get a very similar error to @nsmoller I believe is has something to do with macOS 10.12
