### ISSUE TITLE
Serious errors when coping large buildings to a different world

### ISSUE THREAD

**Issue by TheCherryKing** [mcedit/mcedit2#281]
When I copied a large building to a different world of mine many block IDs got mixed up resulting in serious errors. This building contains items from a variety of mods. I have copied this building in the same world without any problems. All of the items were correct. But when I copy this building to a different world there are many problems. I am using MCEdit 64-Bit. The Minecraft version is 1.8.9. The first three photos show the original building while the next three show the corrupted building.
![2016-10-12_14 50 26](https://cloud.githubusercontent.com/assets/22798286/19323709/0f3b11c2-908c-11e6-9853-7a9264294b38.png)
![2016-10-12_14 50 47](https://cloud.githubusercontent.com/assets/22798286/19323712/14290982-908c-11e6-8790-fede32216c37.png)
![2016-10-12_14 50 05](https://cloud.githubusercontent.com/assets/22798286/19323719/1c5369d6-908c-11e6-9dcf-6853ff7a60a0.png)
![2016-10-12_14 47 25](https://cloud.githubusercontent.com/assets/22798286/19323728/2678fdcc-908c-11e6-9c98-4b7b4f2d4bf0.png)
![2016-10-12_14 47 51](https://cloud.githubusercontent.com/assets/22798286/19323734/2a53a460-908c-11e6-92b5-3fec1f0fff1c.png)
![2016-10-12_14 47 10](https://cloud.githubusercontent.com/assets/22798286/19323745/3224bf4e-908c-11e6-9c16-6aeb7913b224.png)

**Comment by codewarrior0** [comment]
MCEdit 1.0 cannot copy modded blocks to and from different worlds.
