### ISSUE TITLE
Suggesting some documentation adaptions for newcomers.

### ISSUE THREAD

**Issue by AndersBillLinden** [mcedit/mcedit2#289]
I have some suggestions for the documentation in the "getting started sections for windows developers" section:
* which folder?
> Open a bash shell and cd to the folder containing the MCEdit sources.

Can the documentation spell out the folder name, like `src`? Is that the folder btw? (The top level .gitignore ignores an ENV file/folder in any folder, so it could be the root folder as well).
* "Virtual environments"
> Create a virtualenv

Can the virtualenv concept be described for newcomers?
* What is `easy_install`? Is that a script? Could links for information about virtualenvs and easy_install be added?

**Comment by codewarrior0** [comment]
Made some changes. Not my job to introduce newbies to Python, though.
