### ISSUE TITLE
It's not clear how to export a schematic

### ISSUE THREAD

**Issue by Nubebuster** [mcedit/mcedit2#29]
How do I export a schematic from a world in MCEdit 2.0?

**Comment by codewarrior0** [comment]
You can't do that yet. Wait for the next alpha release. 

Closing this issue as it is not a startup failure.

**Comment by Nubebuster** [comment]
When will it be added? I really need it as mcedit v1 exports newly added blocks with very weird ids.
or how do I convert those unknown ids into the new ids?

for example -188 is a beacon (138)

**Comment by codewarrior0** [comment]
I have never heard of MCEdit ever reporting negative block IDs.

Report issues with MCEdit v1 here: https://github.com/Khroki/MCEdit-Unified/issues

**Comment by Nubebuster** [comment]
Thanks.

**Comment by codewarrior0** [comment]
The schematic export will be put in the next alpha release of 2.0, but I would not recommend using it for anything serious until it is in beta.
