### ISSUE TITLE
Weird scripting error while using fill tool

### ISSUE THREAD

**Issue by mc4539** [mcedit/mcedit2#291]
EDIT: It seems that I keep getting the same error now with different blocks. I don't know if this is a rare instance of some bug or the way the program was written. The steps to reproduce this error may not be as helpful, but maybe the error log will give some help to fix this.

I also came across this other error log after restarting MCEdit when experiencing this error:

> An error occurred while opening C:\Users\*\Desktop\mcedit2-win64-2.0.0-beta6\mcedit2.exe
> Cannot detect type of file C:\Users\*\Desktop\mcedit2-win64-2.0.0-beta6\mcedit2.exe.
> 
> Traceback (most recent call last):
>   File "mcedit2\editorapp.py", line 700, in loadFile (self is a MCEditApp)
>   File "mcedit2\editorsession.py", line 182, in __init__ (self is a EditorSession)
>   File "mceditlib\worldeditor.py", line 233, in __init__ (self is a WorldEditor)
>   File "mceditlib\findadapter.py", line 66, in findAdapter  
> UnknownFormatError: Cannot detect type of file C:\Users\*\Desktop\mcedit2-win64-2.0.0-beta6\mcedit2.exe.
> 

---

Hi all,
It seems as if I came across this script error while using the fill tool next to the toolbar text button. I get an error log like this:

> 
> MCEdit version: 2.0.0-beta6
> Python version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
> Platform: win32
> System version: Windows-10-10.0.14393
> Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
> 
> Obtained a GL context with this format:
> Valid: True
> Version: 4.5
> Hardware Accelerated: True
> Depth buffer: True, 24
> Double buffer: True
> Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile
> 
> Driver info:
> GL_VERSION: 4.5.13447 Compatibility Profile Context 16.300.2311.0 (4, 5)
> GL_VENDOR: 'ATI Technologies Inc.'
> GL_RENDERER: 'Radeon (TM) RX 480 Graphics'
> 
> ------
> 
> Unhandled Exception
> 
> Traceback (most recent call last):
>   File "mcedit2\widgets\blockpicker.py", line 322, in showPicker (self is a BlockTypeButton)
>   File "mcedit2\widgets\blockpicker.py", line 317, in blocks (self is a BlockTypeButton)
>   File "mcedit2\widgets\blockpicker.py", line 288, in updateView (self is a BlockTypeButton)
> AttributeError: 'EditorSession' object has no attribute 'textureAtlas'

Steps to reproduce:
1. Open any Minecraft map
2. Select an area of blocks with the select tool
3. Use the fill tool next to the toolbar text button
4. Select Polished Andesite as the fill material
5. There should be an error log that appears with the same error as mine.

**Comment by codewarrior0** [comment]
Allow me to correct your "Steps to reproduce":

1. Open any Minecraft map
1. Close that map
1. Open any Minecraft map
1. Select an area of blocks with the select tool
1. Use the fill tool next to the toolbar text button
1. Select Polished Andesite as the fill material
1. There should be an error log that appears with the same error as mine.
