### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by wordandahalf** [mcedit/mcedit2#293]
MCEdit version: 2.0.0-beta6
Minecraft version: MinecraftForge 1.7 (Forge 10.13.4.1558) with TFC 0.79.29
OS: Windows 10 x64 w/ Anniversary Update
Steps to reproduce: 
Create a new world using the standard TFC generator, explore for a couple thousand blocks a one direction, load into MCEdit.
Result: Near-immediate usage of all system RAM (16GB)
The only error in the log is:
```
[INFO][players.py:35]:Error getting player info: No JSON object could be decoded
[ERROR][player_server.py:85]:Error reading JSON from session server.
Traceback (most recent call last):
  File "mcedit2\util\player_server.py", line 83, in _queryFinished (self is a PlayerDataCache)
  File "json\__init__.py", line 339, in loads  
  File "json\decoder.py", line 364, in decode (self is a JSONDecoder)
  File "json\decoder.py", line 382, in raw_decode (self is a JSONDecoder)
ValueError: No JSON object could be decoded
```

**Comment by manontheinternet** [comment]
A bit late. But, I've been trying to generate a top-down-map called "over" in the options for the last 3 days. I have the hardware, I would think. Good proc and graphics, etc. But, my 12gb of ram just seems to run out of memory at the last second. I'm making the map for my brothers' server. In the past with MCEdit, years ago. I recall no problem like this

**Comment by codewarrior0** [comment]
@manontheinternet It looks like you want to use an overhead mapping tool rather than a world editor. Try one of these: 

http://minecraft.gamepedia.com/Programs_and_editors/Mapping

**Comment by manontheinternet** [comment]
Cool, thanks for something updated. I hope I can take screen shots of my "over" head view and such without it being so low rez. I haven't played since whenever MCEdit, the guy developing was asking for money to make it open source. He asked like 50k USD. He was unemployed for awhile. I guess if I spent my time into that I would do something similar. At least MCEdit was not memory leaking or freezing or crashing; back then.

**Comment by codewarrior0** [comment]
Fixed.
