### ISSUE TITLE
No handlers found for logger "mcedit2.main" 

### ISSUE THREAD

**Issue by EvilSupahFly** [mcedit/mcedit2#30]
Running Linux, Ubuntu 14.04 x64, and MCEdit 2.0.0-alpha1 from source. Program terminates with the following message:

Log level set
No handlers could be found for logger "mcedit2.main"

**Comment by codewarrior0** [comment]
What command did you use to start mcedit2?

**Comment by codewarrior0** [comment]
I see that whatever the actual error is, it's hidden because the logging facility isn't starting up correctly. The next line after "Log level set" ought to be "Logging to <filename>.log". For some reason, it doesn't get all the way through `setup_logging` in mcedit2/main.py and doesn't set up the log outputs.

**Comment by codewarrior0** [comment]
Oh, duh.

Go to line 106 in mcedit2/main.py where you will see these two lines:

```
    sys.excepthook = excepthook
    setup_logging()
```

Swap them around so they look like this:

```
    setup_logging()
    sys.excepthook = excepthook
```

Let me know if it shows you an error about the logging module when you run it then.

**Comment by EvilSupahFly** [comment]
Will do, soon as I get home! :)

**Comment by codewarrior0** [comment]
I pushed that change for you, so you can just `git pull` when you get home.

**Comment by EvilSupahFly** [comment]
Lines swapped and now I'm getting a permission error on a folder that doesn't exist: '/usr/MCEdit User Data'

Was that supposed to be created by the initial setup tool?

**Comment by EvilSupahFly** [comment]
Never mind. I made it myself, had to make it RW by all, and now I have:

ImportError: No module named qt.console.rich_ipython_widget

Which I assume means missing dependencies on my end?

**Comment by EvilSupahFly** [comment]
Also, when being run as a non-root user, why is MCE2 seeking write access in /usr/? Generally only root us allowed to do that.

**Comment by codewarrior0** [comment]
I don't know. It's supposed to create the folder in the source checkout dir (specifically, two levels up from src/mcedit2/main.py). The function responsible is in `src/mcedit2/util/directories.py`. A patch that gets that folder into the right place on Linux would be welcome.

**Comment by codewarrior0** [comment]
That missing dependency might be because of an old version of IPython. I'm using 2.3.1. You can check with `ipython -V`

**Comment by codewarrior0** [comment]
It might be that the line `if exe.endswith("python") or exe.endswith("python.exe"):` should also check for `python27` or `python2.7` or `python2` - some linux distros name it like that since the "system python" is set to python 3.

**Comment by EvilSupahFly** [comment]
Well there's part of my problem.

My install reports v1.2.1. That's getting fixed right now. As for paths in Linux, I don't know how Python handles paths internally, but "../../" would set the path 2 levels up from the current working directory.

**Comment by EvilSupahFly** [comment]
APT reports ipython as being current... Guess I have to go the long way.

**Comment by EvilSupahFly** [comment]
Using PIP, IPython updated to 2.4 and now MCE2 is running!

**Comment by codewarrior0** [comment]
Yep. Can't rely on the distros giving you the right versions of everything, so that's what virtualenv is for. I'll have to go to requirements.txt again and pin a few versions to be sure.

 I'm pretty sure the user data folder landing in `/usr` is due to the `python27` thing, so I'll be changing that when I update that function to use the right folder in Documents or whatever for a regular per-user install.

**Comment by EvilSupahFly** [comment]
The user's home folder is likely the best place for the log file anyway. No need to tangle with permissions. :-)

**Comment by EvilSupahFly** [comment]
Also, you may be interested in knowing that there's an iPython PPA on launchpad (which I only found after the fact!), so users of Debian Linux (and it's derivatives) can add it and get the latest stable release through APT (if they're so inclined).

https://launchpad.net/~jtaylor/+archive/ubuntu/ipython
