### ISSUE TITLE
Mcedit developer

### ISSUE THREAD

**Issue by DRwilli** [mcedit/mcedit2#305]
Je vous propose de créer des setup pour votre application pour mieux installer les programmes et les mieux les utiliser

Contactez-moi sur mon adresse email qui est : auger77777@gmail.com

I propose to create setup for your application to better install programs and better use them

Contact me on my email address which is : auger77777@gmail.com

Download Setup : https://mega.nz/#!81VUBACY!KP0lcRoaT1ZxsVQi-pSyA3Op_itSs3RKSlolMwR1zb4

Télécharger jeu script : https://mega.nz/#!FksXTJAY!PbZeiYXtchvrdVaYl5Kty5tNzGTvzoiwKhBoqUno3is

Launch as Administrator

**Comment by codewarrior0** [comment]
>Download Setup
>Launch as Administrator

Nope.
