### ISSUE TITLE
mcedit2 hangs up with "loading plugins... 37%" while loading a 1.11.2 world

### ISSUE THREAD

**Issue by ShelLuser** [mcedit/mcedit2#309]
Windows 7, 32bit, Minecraft version 1.11.2, MCEdit2 (mcedit2-win32-2.0.0-beta7). I normally play using the latest Optifine (1.11.2-OptiFine_HD_U_B7) but I also tried using this on a strictly vanilla Minecraft (1.11.2) created world. Same thing. Although I also play with a resource pack I never selected it during loading to avoid issues.

The selection screen is shown, I select 1.11.2, then select the world I want to download and click Edit. The selection screen disappears and a loading pop-up shows, which initially stalls at 37%. The tracelog can be found here:

https://pastebin.com/t6hNbEAa

What I also considered highly peculiar is that MCEdit tries to start GIT yet doesn't provide a correct command and thus triggers an error, see this:

![git](https://cloud.githubusercontent.com/assets/25201078/24365354/f56a7398-1315-11e7-87f5-7e65525b4e56.jpg)

The "_fatal: not a git repository_" error was triggered by GIT which is available in my search path. I think it's a peculiar error and I'm not too sure that I like the idea of mcedit trying to pull in files without my knowledge.

**Comment by codewarrior0** [comment]
Even though you didn't select a resource pack, MCEdit seems to be using one called `Lithos-Core`. I wonder why...

```
[INFO][minecraftinstall.py:486]:Created ResourceLoader with search path:
C:\Users\Peter\AppData\Roaming\.minecraft\resourcepacks\Lithos-Core v1.14 for 1.11x.zip (ce3af0dae4fb0a5a7f5c1a95e8f9687b),
C:\Users\Peter\AppData\Roaming\.minecraft\versions\1.11.2\1.11.2.jar (9dd50a2e6a74f7e186354250c2f2c635),
C:\Users\Peter\AppData\Roaming\.minecraft\versions\1.11.2\1.11.2.jar (9dd50a2e6a74f7e186354250c2f2c635)
```

**Comment by codewarrior0** [comment]
The hang at 37% was from incorrectly looking up texture variables. The new method cannot hang.
