### ISSUE TITLE
Seeing the wrong stuff

### ISSUE THREAD

**Issue by jlkfreeman1** [mcedit/mcedit2#31]
When you look at a nether brick fence in MCEdit, you see a nether brick block.
I would like it iif you could fix this. Thanks, jlkfreeman1 ;)

**Comment by jlkfreeman1** [comment]
Anyone want ta help?

**Comment by codewarrior0** [comment]
Which version?

**Comment by jlkfreeman1** [comment]
2.0 I think

**Comment by jlkfreeman1** [comment]
Thanks for commenting ;)

**Comment by jlkfreeman1** [comment]
When I look at a Nether Brick Fence in MCEdit, it shows up looking like a Nether Brick

**Comment by jlkfreeman1** [comment]
Wait ill BRB

**Comment by codewarrior0** [comment]
Only report startup failures in MCEdit 2.0 alpha. Closing this issue as invalid.

**Comment by jlkfreeman1** [comment]
AsShole

**Comment by jlkfreeman1** [comment]
god

**Comment by codewarrior0** [comment]
If you curse at me again, you will be blocked.
