### ISSUE TITLE
Error importing schematics

### ISSUE THREAD

**Issue by KoiYT** [mcedit/mcedit2#311]
![no import](https://cloud.githubusercontent.com/assets/27504402/25065122/ffd4bc40-2200-11e7-9041-8778e43832b4.jpg)
Error log is in the screenshot above.
Schematics > import > select schematic to import then click open
I'm using 2.0.0 beta 6.
I'm using 1.11 with optifine HD.
I'm using 64 bit Windows 10 version 1607.

**Comment by codewarrior0** [comment]
Can't help you without a copy of the file in question.
