### ISSUE TITLE
mcedit 2 won't recognize forge 1.11.2

### ISSUE THREAD

**Issue by pathcat** [mcedit/mcedit2#315]
hi, there;

i saw someone else had this problem too but the thread was closed. however my mcedit is now doing it as well. i have forge 1.11.2 installed and i've been using it regularly but mcedit won't list it in the dropdown. i have the latest update and i'm running windows 10. can you help?

thanks
cat

**Comment by pathcat** [comment]
hellooo? anyone here?

**Comment by codewarrior0** [comment]
MCEdit does not automatically detect your Forge install. Use the "Configure Installations" button to add it.
