### ISSUE TITLE
Iron farms won't work after moving them by mcedit 2.0 to other worlds

### ISSUE THREAD

**Issue by kouroshkhan** [mcedit/mcedit2#317]
I downloaded an iron farm and make the schematic of that farm then import it to my world but after that it stops working on my world I guess the villages will disappear.so how can I solve this problem.

**Comment by codewarrior0** [comment]
Village data is not stored in schematic files. You may need to edit the `villages.dat` by hand, or else import the iron farm onto an existing village.
