### ISSUE TITLE
MCEdit 2 Beta 7 - Crash after selecting "Edit"

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [mcedit/mcedit2#325]
MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.10586
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 378.49 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 970/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\widgets\inventory.py", line 54, in data (self is a InventoryItemModel)
  File "mceditlib\anvil\entities.py", line 150, in getItemInSlot (self is a SlotsListProxy)
  File "mceditlib\nbtattr.py", line 84, in __get__ (self is a NBTAttr)(named Slot)
ValueError: (u'No default value set for tag %r.', u'Slot')

**Comment by codewarrior0** [comment]
Cannot reproduce. (Which "Edit" did you click?)
