### ISSUE TITLE
its not working and im trying to make something for my best friend

### ISSUE THREAD

**Issue by bowmandaniel** [mcedit/mcedit2#328]
MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.14393
Processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.4
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.4.0 - Build 20.19.15.4300 (4, 4)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 530'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\panels\map.py", line 40, in data (self is a MapListModel)
  File "mcedit2\panels\map.py", line 54, in imageForMapID (self is a MapListModel)
  File "mceditlib\anvil\adapter.py", line 1129, in getColorsAsRGBA (self is a AnvilMapData)
IndexError: index 182 is out of bounds for axis 0 with size 144

**Comment by codewarrior0** [comment]
Related to version 1.12 which MCEdit does not yet support.
