### ISSUE TITLE
MCEdit2 Error

### ISSUE THREAD

**Issue by Thekillardog** [mcedit/mcedit2#33]
When I open up mc edit, it starts working fine then it does some weird error thing about 50 times in the cmd window. Is there any way to fix that?

**Comment by codewarrior0** [comment]
Post your MCEdit version and log file as required in the [reporting guidelines](https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md).

**Comment by codewarrior0** [comment]
Closing as invalid. Read the reporting guidelines before opening another issue.
