### ISSUE TITLE
Redstone wire not rendered properly

### ISSUE THREAD

**Issue by Mathe172** [mcedit/mcedit2#340]
As the title says, redstone wire is not rendered properly, only dots and wires on the sides of blocks are visible at all.
Screenshot:
![image](https://user-images.githubusercontent.com/3540742/27781712-755b648a-5fcf-11e7-82d6-4dbcb3bd6c7b.png)

Log: [mcedit2.log.txt](https://github.com/mcedit/mcedit2/files/1118710/mcedit2.log.txt)
Steps to reproduce: Open any world, (View or Edit) and look for redstone
MCEdit version: MCEdit 2.0.0-beta9
Minecraft version: 1.12 (checked older versions, both by just selecting one in MCEdit and opening worlds from older versions, doesn't matter)
Operating system: Windows 10 Pro 64-bit, Version 1703 (build 15063.413) (Creators Update)
GPU: Tested on a MS Surface Book with both iGPU (Intel HD 520) and dGPU (Custom NVidia, ~GTX 940M), latest drivers

**Comment by codewarrior0** [comment]
Fixed.

**Comment by Mathe172** [comment]
Thanks a lot. Keep up the great work!
