### ISSUE TITLE
MCEdit 2.0.0-beta8 not start

### ISSUE THREAD

**Issue by Rambo99** [mcedit/mcedit2#343]
The program does not start. After starting the program, a black window appears and after 3-5 seconds it disappears, but the program does not start. The only thing that was noticed in the "black window" is a couple of lines with errors. Here they are -

Traceback (most recent last call last):
File "mcedit2 \ main.ry", line 15, in <module>
File "c: \ python27-x64 \ lib \ site-packages \ PyInstaller \ loader \ pyimod03_importers.py", line 396, in load_module
File "mcedit2 \ sentry.py", line 4, in <module>
ImportError: no module named raven
Failed to execute script main

I tried several times, but the result does not change. I downloaded the file from your site several times thought an error while downloading. Did not help. The error is observed on both versions (32 bits and 64 bits).

**Comment by codewarrior0** [comment]
beta8 is no longer available. Where did you download it from?

**Comment by Rambo99** [comment]
From your website(.http://www.mcedit.net/downloads.html) about 10 days ago.
