### ISSUE TITLE
No support for 1.12?

### ISSUE THREAD

**Issue by tyler489** [mcedit/mcedit2#347]
I had a crash with a mod and i was going to use mcedit to remove the offending block and when i went to the world version tab the higest version was 1.11.2 Will this cause issues?

**Comment by codewarrior0** [comment]
If you install 1.12 using the official Minecraft launcher, it should show up in the version tab.

**Comment by tyler489** [comment]
ok im stupid.... 2 more things why is the world READ ONLY. and how the heck do i delete blocks...

**Comment by codewarrior0** [comment]
Did you click "View" instead of "Edit"?
