### ISSUE TITLE
Pyinstaller fails to build executable for MCEdit2

### ISSUE THREAD

**Issue by theCodeSpewer** [mcedit/mcedit2#348]
Operating System: Linux Mint 18.1 64-bit
MCEdit2 Version: 2.0.0-beta11 (however this version of MCEdit that I am using is not the stable release of beta11 but an up-to-date clone of the GitHub repository which was cloned on the 25th July.
Minecraft Version Number: Not specific (this does not involve the actual startup of MCEdit so the Minecraft version is not necessary)

Commands executed in Terminal which have lead to the issue:

~ $ cd mcedit2 #go into the directory where MCEdit2 is installed
~/mcedit2 $ source mcedit2-env/bin/activate #activate Python virtual environment
(mcedit2-env) ~/mcedit2 $ pyinstaller mcedit2.spec #attempt to build the executable file using PyInstaller

Please note that the name of the virtual environment is not "ENV", as requested in the README.md file but "mcedit2-env" because when the virtual environment is active, I know that I am using the virtual environment of MCEdit2 and not any other virtual environment that I have on my system. This is to prevent confusion between names. I also presume that the difference in the name of the virtual environment has no overall effect on the behaviour of the program.

Here is the entire console output of the last command:

135 INFO: PyInstaller: 3.3.dev0+g4fd7988.mod
135 INFO: Python: 2.7.12
135 INFO: Platform: Linux-4.10.0-27-generic-x86_64-with-LinuxMint-18.1-serena
168 INFO: UPX is not available.
running develop
running egg_info
writing requirements to src/mcedit2.egg-info/requires.txt
writing src/mcedit2.egg-info/PKG-INFO
writing top-level names to src/mcedit2.egg-info/top_level.txt
writing dependency_links to src/mcedit2.egg-info/dependency_links.txt
writing entry points to src/mcedit2.egg-info/entry_points.txt
reading manifest file 'src/mcedit2.egg-info/SOURCES.txt'
writing manifest file 'src/mcedit2.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/blockmodels.so -> src/mcedit2/rendering
copying build/lib.linux-x86_64-2.7/mcedit2/rendering/modelmesh.so -> src/mcedit2/rendering
Creating /home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages/mcedit2.egg-link (link to src)
mcedit2 2.0.0a1.dev0 is already the active version in easy-install.pth
Installing mcedit2 script to /home/<username>/mcedit2/mcedit2-env/bin

Installed /home/<username>/mcedit2/src
Processing dependencies for mcedit2==2.0.0a1.dev0
Searching for numpy==1.13.0
Best match: numpy 1.13.0
Adding numpy 1.13.0 to easy-install.pth file

Using /home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages
Finished processing dependencies for mcedit2==2.0.0a1.dev0
running develop
running egg_info
writing requirements to src/mceditlib.egg-info/requires.txt
writing src/mceditlib.egg-info/PKG-INFO
writing top-level names to src/mceditlib.egg-info/top_level.txt
writing dependency_links to src/mceditlib.egg-info/dependency_links.txt
reading manifest file 'src/mceditlib.egg-info/SOURCES.txt'
writing manifest file 'src/mceditlib.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/mceditlib/nbt.so -> src/mceditlib
copying build/lib.linux-x86_64-2.7/mceditlib/relight/with_cython.so -> src/mceditlib/relight
Creating /home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages/mceditlib.egg-link (link to src)
mceditlib 2.0.0a1.dev0 is already the active version in easy-install.pth

Installed /home/<username>/mcedit2/src
Processing dependencies for mceditlib==2.0.0a1.dev0
Searching for numpy==1.13.0
Best match: numpy 1.13.0
Adding numpy 1.13.0 to easy-install.pth file

Using /home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages
Finished processing dependencies for mceditlib==2.0.0a1.dev0

fatal: destination path 'mcedit2-lang' already exists and is not an empty directory.
Traceback (most recent call last):
  File "/home/<username>/mcedit2/mcedit2-env/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.dev0+g4fd7988.mod', 'console_scripts', 'pyinstaller')()
  File "/home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages/PyInstaller-3.3.dev0+g4fd7988.mod-py2.7.egg/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages/PyInstaller-3.3.dev0+g4fd7988.mod-py2.7.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages/PyInstaller-3.3.dev0+g4fd7988.mod-py2.7.egg/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/<username>/mcedit2/mcedit2-env/lib/python2.7/site-packages/PyInstaller-3.3.dev0+g4fd7988.mod-py2.7.egg/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 84, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/mcedit/mcedit2-lang', '--depth', '1']' returned non-zero exit status 128

**Comment by codewarrior0** [comment]
Shrug. PyInstaller gets run on AppVeyor and Travis CI instances so it gets a clean git clone each time.
