### ISSUE TITLE
KeyError: 'End'

### ISSUE THREAD

**Issue by Mezlo** [mcedit/mcedit2#35]
MCEdit v1.3.00 Unified for Minecraft 1.8 (64bit)

When attempting to change the biome to The End using the setbiome filter, it returns a KeyError. Changing "End" to "The End" in stock-filters\setbiome.py, line 26, resolves the issue.

**Comment by OniOniOn-** [comment]
Report MCEdit 1.0 issues here: https://github.com/Khroki/MCEdit-Unified/issues
Marking the issue as invalid.

**Comment by OniOniOn-** [comment]
Report MCEdit 1.0 issues here: https://github.com/Khroki/MCEdit-Unified/issues
Closing this issue as invalid.
