### ISSUE TITLE
"pip install -r requirements.txt" error: MCedit doesn't start

### ISSUE THREAD

**Issue by Dhrhciebcy** [mcedit/mcedit2#350]
My terminal reports this error after the "pip install -r requirements.txt" command:

(ENV) dhrhciebcy@VEGAS:~/Scrivania/mcedit2-master$ pip install -r requirements.txt
Requirement already satisfied: cython in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 1))
Requirement already satisfied: numpy in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 2))
Requirement already satisfied: arrow in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 3))
Requirement already satisfied: pyzmq==15.0.0 in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Collecting pyside>=1.2.0 (from -r requirements.txt (line 3))
  Using cached PySide-1.2.4.tar.gz
Collecting pyopengl (from -r requirements.txt (line 4))
Collecting ipython (from -r requirements.txt (line 5))
  Using cached ipython-5.4.1-py2-none-any.whl
Collecting qtconsole (from -r requirements.txt (line 6))
  Using cached qtconsole-4.3.0-py2.py3-none-any.whl
Collecting pygments (from -r requirements.txt (line 7))
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting pastebin (from -r requirements.txt (line 8))
Collecting raven (from -r requirements.txt (line 9))
  Using cached raven-6.1.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in ./ENV/lib/python2.7/site-packages (from arrow->-r requirements-mceditlib.txt (line 3))
Collecting pickleshare (from ipython->-r requirements.txt (line 5))
  Using cached pickleshare-0.7.4-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython->-r requirements.txt (line 5))
Collecting traitlets>=4.2 (from ipython->-r requirements.txt (line 5))
  Using cached traitlets-4.3.2-py2.py3-none-any.whl
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython->-r requirements.txt (line 5))
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting decorator (from ipython->-r requirements.txt (line 5))
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython->-r requirements.txt (line 5))
  Using cached pexpect-4.2.1-py2.py3-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython->-r requirements.txt (line 5))
  Using cached pathlib2-2.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5))
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython->-r requirements.txt (line 5))
  Using cached prompt_toolkit-1.0.14-py2-none-any.whl
Collecting jupyter-core (from qtconsole->-r requirements.txt (line 6))
  Using cached jupyter_core-4.3.0-py2.py3-none-any.whl
Collecting jupyter-client>=4.1 (from qtconsole->-r requirements.txt (line 6))
  Using cached jupyter_client-5.1.0-py2.py3-none-any.whl
Collecting ipykernel>=4.1 (from qtconsole->-r requirements.txt (line 6))
  Using cached ipykernel-4.6.1-py2-none-any.whl
Collecting ipython-genutils (from qtconsole->-r requirements.txt (line 6))
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting contextlib2 (from raven->-r requirements.txt (line 9))
  Using cached contextlib2-0.5.5-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in ./ENV/lib/python2.7/site-packages (from python-dateutil->arrow->-r requirements-mceditlib.txt (line 3))
Collecting enum34; python_version == "2.7" (from traitlets>=4.2->ipython->-r requirements.txt (line 5))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->-r requirements.txt (line 5))
  Using cached ptyprocess-0.5.2-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython->-r requirements.txt (line 5))
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython->-r requirements.txt (line 5))
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting tornado>=4.0 (from ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
Collecting singledispatch (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting certifi (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
  Using cached backports_abc-0.5-py2.py3-none-any.whl
Building wheels for collected packages: pyside
  Running setup.py bdist_wheel for pyside ... error
  Complete output from command /home/dhrhciebcy/Scrivania/mcedit2-master/ENV/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g2OAv5/pyside/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2KMztYpip-wheel- --python-tag cp27:
  Removing /tmp/pip-build-g2OAv5/pyside/pyside_package
  running bdist_wheel
  running build
  Python architecture is 64bit
  qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
  Failed to query the Qt version with qmake /usr/bin/qmake
  
  ----------------------------------------
  Failed building wheel for pyside
  Running setup.py clean for pyside
Failed to build pyside
Installing collected packages: pyside, pyopengl, scandir, pathlib2, pickleshare, simplegeneric, enum34, decorator, ipython-genutils, traitlets, backports.shutil-get-terminal-size, pygments, ptyprocess, pexpect, wcwidth, prompt-toolkit, ipython, jupyter-core, jupyter-client, singledispatch, certifi, backports-abc, tornado, ipykernel, qtconsole, pastebin, contextlib2, raven
  Running setup.py install for pyside ... error
    Complete output from command /home/dhrhciebcy/Scrivania/mcedit2-master/ENV/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g2OAv5/pyside/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-CjD7sG-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dhrhciebcy/Scrivania/mcedit2-master/ENV/include/site/python2.7/pyside:
    Removing /tmp/pip-build-g2OAv5/pyside/pyside_package
    running install
    running build
    Python architecture is 64bit
    qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
    Failed to query the Qt version with qmake /usr/bin/qmake
    
    ----------------------------------------
Command "/home/dhrhciebcy/Scrivania/mcedit2-master/ENV/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g2OAv5/pyside/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-CjD7sG-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dhrhciebcy/Scrivania/mcedit2-master/ENV/include/site/python2.7/pyside" failed with error code 1 in /tmp/pip-build-g2OAv5/pyside/
(ENV) dhrhciebcy@VEGAS:~/Scrivania/mcedit2-master$ mcedit2
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/dhrhciebcy/Scrivania/mcedit2-master/ENV/bin/mcedit2", line 11, in <module>
    load_entry_point('mcedit2', 'console_scripts', 'mcedit2')()
  File "/home/dhrhciebcy/Scrivania/mcedit2-master/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dhrhciebcy/Scrivania/mcedit2-master/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/dhrhciebcy/Scrivania/mcedit2-master/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/dhrhciebcy/Scrivania/mcedit2-master/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dhrhciebcy/Scrivania/mcedit2-master/src/mcedit2/main.py", line 13, in <module>
    import OpenGL
ImportError: No module named OpenGL
(ENV) dhrhciebcy@VEGAS:~/Scrivania/mcedit2-master$ 

My OS is Ubuntu 16.04 LTS

Please help :(

**Comment by juozaspo** [comment]
To build pyside successfully you nead **qt4-qmake** and **libqt4-dev** packages with their dependencies on your host ubuntu system, since it tries to build a lot of qt stuff. I found about it by googling 'Running setup.py install for pyside ... error' and then viewing some results i found. Looking to task manager it appears there's a lot pyside and qt directories and files in build path since it's so much tied to qt. On my machine it takes a load of time to build and I don't know if it will build successfully since it's not done yet as I'm writing this comment.

**Comment by Dhrhciebcy** [comment]
Ok I will try. Thanks very much

**Comment by juozaspo** [comment]
You might also check https://wiki.qt.io/Building_PySide_on_Linux how to build PySide, there's a detailed documentation there.

**Comment by Dhrhciebcy** [comment]
GREAT!!! IT WORKS!!! Mcedit2 starts without problems!!! Yeeessss!!!
Thanks very much!!!
