### ISSUE TITLE
Entity

### ISSUE THREAD

**Issue by GhostShot3** [mcedit/mcedit2#354]
I can not see entities once I load my world in 1.2
I read the guidlines.

**Comment by GhostShot3** [comment]
I read the guidelines!!!

**Comment by GhostShot3** [comment]
What is wrong here ?

**Comment by DeGariless** [comment]
https://github.com/mcedit/mcedit2/wiki/Reporting-Issues

**Comment by GhostShot3** [comment]
What is wrong here ?²
