### ISSUE TITLE
MCEDIT WONT DOWNLOAD PLEASE HELP

### ISSUE THREAD

**Issue by NEEDHELPPERSONMAN** [mcedit/mcedit2#356]
so basically i got to mcedit.net then click downloads and click 2.0.0-beta11 windows(64bit) download button. It starts to download but a minute or two into the download it says failed- forbidden and doesnt download

**Comment by codewarrior0** [comment]
Try again later.

**Comment by NEEDHELPPERSONMAN** [comment]
this didnt help at all
