### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by Azounstone** [mcedit/mcedit2#359]
When launching the product it generates the following error:

![mcedit 2](https://user-images.githubusercontent.com/9461336/29005850-6dbe7ef6-7adc-11e7-94ae-77edd610489d.jpg)

I am using MCEdit 2 beta release 2.0.0-beta11 and Minecraft 1.11.2

Do you know how I can fix this so that I may test this product?

**Comment by codewarrior0** [comment]
Download Minecraft 1.12 using the official launcher, or try again later,
