### ISSUE TITLE
Can't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by OscarOrSomething** [mcedit/mcedit2#36]
`pip install -r requirements.txt` fails, log: http://pastebin.com/P1QV5d4e

**Comment by ComputerCandy** [comment]
you are downloading .exe they are not the ubuntu files. If you want to use the .exe use WINE (Windows Program Loader)

**Comment by OscarOrSomething** [comment]
I'm not downloading any exe, they are getting skipped by pip as they aren't recognized (188-198).

**Comment by ComputerCandy** [comment]
odd =/

**Comment by codewarrior0** [comment]
It's trying to build Qt from scratch. See if you can install PySide for py2.7 using Ubuntu's package manager instead. (apt-get? aptitude?) It should pull in a prebuilt Qt.

**Comment by OscarOrSomething** [comment]
I installed python-pyside but it still doesn't work.

**Comment by codewarrior0** [comment]
You'll have to figure out how to get the system installed PySide into the virtualenv, or else remove the virtualenv and run MCEdit using only system installed packages.
