### ISSUE TITLE
Need help need A getWorldVersion() method

### ISSUE THREAD

**Issue by StealthyExpertX** [mcedit/mcedit2#371]
I need A method for the MCEdit v2.0 Plugin api like getWorldVersion(true) that would return the version 
of the mc world thats loaded like as A string value if true if false would return as an int value.

the output would be "1.7" or 1.12.2 for example

I need this to make my plugins compatible with older updates of mc or newer updates in the future.

**Comment by codewarrior0** [comment]
1bd31fbd2cfc24e034274b7a7609af6afda73335

**Comment by StealthyExpertX** [comment]
THANKS
