### ISSUE TITLE
error: Failed to locate the Python library

### ISSUE THREAD

**Issue by tuxutku** [mcedit/mcedit2#372]
distribution is clear linux (similar to slackware) 

<pre>
(ENV) utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mcedit2 $ uname -a
Linux clr-449e9b2a44f8458bb4885604dc172a1c 4.14.3-482.native #2 SMP Thu Nov 30 12:15:31 UTC 2017 x86_64 GNU/Linux
</pre>

<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mcedit2 $ virtualenv -p python2 ENV
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/utku/Programlar/mcedit2/ENV/bin/python2
Also creating executable in /home/utku/Programlar/mcedit2/ENV/bin/python
Installing setuptools, pip, wheel...done.
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mcedit2 $ . ENV/bin/activate
(ENV) utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/mcedit2 $ pip install -r requirements.txt
Requirement already satisfied: cython in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 1))
Requirement already satisfied: numpy in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 2))
Requirement already satisfied: arrow in ./ENV/lib/python2.7/site-packages (from -r requirements-mceditlib.txt (line 3))
Requirement already satisfied: pyzmq==15.0.0 in ./ENV/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Collecting pyside>=1.2.0 (from -r requirements.txt (line 3))
  Using cached PySide-1.2.4.tar.gz
Collecting pyopengl (from -r requirements.txt (line 4))
Collecting ipython (from -r requirements.txt (line 5))
  Using cached ipython-5.5.0-py2-none-any.whl
Collecting qtconsole (from -r requirements.txt (line 6))
  Using cached qtconsole-4.3.1-py2.py3-none-any.whl
Collecting pygments (from -r requirements.txt (line 7))
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting pastebin (from -r requirements.txt (line 8))
Collecting raven (from -r requirements.txt (line 9))
  Using cached raven-6.3.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in ./ENV/lib/python2.7/site-packages (from arrow->-r requirements-mceditlib.txt (line 3))
Requirement already satisfied: backports.functools-lru-cache==1.2.1 in ./ENV/lib/python2.7/site-packages (from arrow->-r requirements-mceditlib.txt (line 3))
Collecting decorator (from ipython->-r requirements.txt (line 5))
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython->-r requirements.txt (line 5))
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython->-r requirements.txt (line 5))
Collecting traitlets>=4.2 (from ipython->-r requirements.txt (line 5))
  Using cached traitlets-4.3.2-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython->-r requirements.txt (line 5))
  Using cached prompt_toolkit-1.0.15-py2-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython->-r requirements.txt (line 5))
  Using cached pathlib2-2.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in ./ENV/lib/python2.7/site-packages (from ipython->-r requirements.txt (line 5))
Collecting pickleshare (from ipython->-r requirements.txt (line 5))
  Using cached pickleshare-0.7.4-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython->-r requirements.txt (line 5))
  Using cached pexpect-4.3.0-py2.py3-none-any.whl
Collecting ipython-genutils (from qtconsole->-r requirements.txt (line 6))
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting jupyter-client>=4.1 (from qtconsole->-r requirements.txt (line 6))
  Using cached jupyter_client-5.1.0-py2.py3-none-any.whl
Collecting ipykernel>=4.1 (from qtconsole->-r requirements.txt (line 6))
  Using cached ipykernel-4.6.1-py2-none-any.whl
Collecting jupyter-core (from qtconsole->-r requirements.txt (line 6))
  Using cached jupyter_core-4.4.0-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3.2" (from raven->-r requirements.txt (line 9))
  Using cached contextlib2-0.5.5-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in ./ENV/lib/python2.7/site-packages (from python-dateutil->arrow->-r requirements-mceditlib.txt (line 3))
Collecting enum34; python_version == "2.7" (from traitlets>=4.2->ipython->-r requirements.txt (line 5))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython->-r requirements.txt (line 5))
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython->-r requirements.txt (line 5))
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->-r requirements.txt (line 5))
  Using cached ptyprocess-0.5.2-py2.py3-none-any.whl
Collecting tornado>=4.0 (from ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
Collecting singledispatch (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting certifi (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=4.0->ipykernel>=4.1->qtconsole->-r requirements.txt (line 6))
  Using cached backports_abc-0.5-py2.py3-none-any.whl
Building wheels for collected packages: pyside
  Running setup.py bdist_wheel for pyside ... error
  Complete output from command /home/utku/Programlar/mcedit2/ENV/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-azkqeQ/pyside/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpo1oYMwpip-wheel- --python-tag cp27:
  Removing /tmp/pip-build-azkqeQ/pyside/pyside_package
  running bdist_wheel
  running build
  Python architecture is 64bit
  error: Failed to locate the Python library with /usr/lib/libpython2.7.so, /usr/lib/libpython2.7.so.1, /usr/lib/libpython2.7.a
  
  ----------------------------------------
  Failed building wheel for pyside
  Running setup.py clean for pyside
Failed to build pyside
Installing collected packages: pyside, pyopengl, pygments, decorator, backports.shutil-get-terminal-size, simplegeneric, enum34, ipython-genutils, traitlets, wcwidth, prompt-toolkit, scandir, pathlib2, pickleshare, ptyprocess, pexpect, ipython, jupyter-core, jupyter-client, singledispatch, certifi, backports-abc, tornado, ipykernel, qtconsole, pastebin, contextlib2, raven
  Running setup.py install for pyside ... error
    Complete output from command /home/utku/Programlar/mcedit2/ENV/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-azkqeQ/pyside/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-JnmzMl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/utku/Programlar/mcedit2/ENV/include/site/python2.7/pyside:
    Removing /tmp/pip-build-azkqeQ/pyside/pyside_package
    running install
    running build
    Python architecture is 64bit
    error: Failed to locate the Python library with /usr/lib/libpython2.7.so, /usr/lib/libpython2.7.so.1, /usr/lib/libpython2.7.a
    
    ----------------------------------------
Command "/home/utku/Programlar/mcedit2/ENV/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-azkqeQ/pyside/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-JnmzMl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/utku/Programlar/mcedit2/ENV/include/site/python2.7/pyside" failed with error code 1 in /tmp/pip-build-azkqeQ/pyside/
</pre>

Libraries in directories:
[usr/lib](https://github.com/mcedit/mcedit2/files/1527850/usr_lib.txt)
[usr/lib64](https://github.com/mcedit/mcedit2/files/1527851/usr_lib64.txt)
[usr/local](https://github.com/mcedit/mcedit2/files/1527852/usr_local.txt)
[usr/local/lib](https://github.com/mcedit/mcedit2/files/1527853/usr_local_lib.txt)

**Comment by codewarrior0** [comment]
You might need to install PySide using the slackware package manager.

**Comment by tuxutku** [comment]
Never mind i succesfully installed mcedit2 but i had to fix shiboken source code that pyside dependet on ,  here is my pull request:
https://github.com/pyside/Shiboken/pull/88
And here is the issue that i replied on:
https://github.com/pyside/Shiboken/issues/85

Note: if someone is trying to compile shiboken, but make returns with:
<pre>
/usr/bin/ld: cannot open output file shiboken: Is a directory
</pre>
 please go to the issue page,
İ have commented how to fix the issue with my reply
