### ISSUE TITLE
Can't edit the world.

### ISSUE THREAD

**Issue by Xtreme533** [mcedit/mcedit2#373]
Hello, I've been trying to edit my map, it worked before, but now for some reason it just won't load (The version is beta11).
My MC version is 1.12.2.

> An error occurred while opening C:\Users\PC\AppData\Roaming\.minecraft\saves\New World-
a float is required

> Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 781, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 190, in __init__ (self is a EditorSession)
TypeError: a float is required 

Help?

**Comment by codewarrior0** [comment]
Already fixed for next release.

**Comment by Ozitec** [comment]
I have the Beta12 and it's still not fixed for me.
