### ISSUE TITLE
Multiple Critical Errors both in Classic MCEdit and MCEdit 2

### ISSUE THREAD

**Issue by TBlazeWarriorT** [mcedit/mcedit2#375]
Entities on my map are giving me error messages when I try to move, rotate or clone them (unhashable type: nbt.tag_string). I also got another weird error when I tried exporting and importing a building with entities on it to another map (index 65535 is out of bounds for axis 0 with size 4096).
I tried rotating a few blocks on MCEdit2 and I got an error message (I think it was the same error as nbt.tag_string from MCEdit1, I can do it again and screenshot it if really necessary), then I tried to still rotate it and save the map. When I went back to Minecraft and opened the map, most of the command blocks that were on the rotated part were now blank, item frames dropped to the ground, signs went invisible and became blank.

Details and specs:
I don't feel like those matter for this specific error, but they'll still be included.
Windows 10 (latest version), GTX 750, i3 3210
MCEdit v1.5.6.0 (latest version I believe)
mcedit2-win64-2.0.0-beta11
Minecraft 1.12.2 with optifine

Reproducing the error:
The errors should pop up in any version of MCEdit and MCEdit2.
Download the map included below and select a few sections of blocks and entities, for example, the huge building contained on the map, and try to move it or rotate it. If I do that, I will for sure get an error message or it simply won't work or delete parts of my building. If you select just grass, for example, everything will work normally.

Error screenshots:
![image](https://user-images.githubusercontent.com/25572454/34057782-8d17a9d6-e1bf-11e7-8f8b-489723f1bd17.png)

![image](https://user-images.githubusercontent.com/25572454/34058582-ab5049a0-e1c2-11e7-9e19-14c64cd562cc.png)

MCEdit log:
The MCEdit log is too big for pastebin, actually. "You have exceeded the maximum paste size of 512 kilobytes per paste. PRO users don't have this limit!" so I uploaded it directly here:
MCEdit2 Log:
[mcedit2.log](https://github.com/mcedit/mcedit2/files/1563857/mcedit2.log)
MCEdit Log:
[mcedit.log](https://github.com/mcedit/mcedit2/files/1563858/mcedit.log)

World savefile:
http://www.mediafire.com/file/b851yal8bq5zy84/Shop.rar

**Comment by TBlazeWarriorT** [comment]
Sorry for a few missing screenshots from the MCEdit2 errors and any missing info, please tell me if I forgot something important! I was lazy and a bit short on time

**Comment by codewarrior0** [comment]
Report MCEdit 1 errors here: https://github.com/Khroki/MCEdit-Unified/issues

When you get the time, open a new issue for me with *only* MCEdit 2 errors.
