### ISSUE TITLE
(Enhancement)  Selection and import location by coordinates

### ISSUE THREAD

**Issue by CleanerOrc** [mcedit/mcedit2#38]
(Enhancement suggestion)

The one thing that I miss in making selections and importing schematics in MCEdit 1.3.0.0 and earlier is the ability to create a selection by typing the upper and lower corner coordinates.

Also the ability to specify the origin coordinates for importing a schematic.  

It would really make it easier to import / export multiple areas if there was a way to specify by coordinates, rather than only by visual location.   You could use the specified coordinates to create the selection box, then be able to move it.  Correspondingly, if you entered import origin coords, these could be used just to initially position the import, then it could be adjusted visually.

**Comment by codewarrior0** [comment]
Read the reporting guidelines again. This is not the MCEdit 1.3.0 issue tracker.

https://github.com/Khroki/MCEdit-Unified/issues
