### ISSUE TITLE
Question regarding MCPE Support

### ISSUE THREAD

**Issue by MetaKnight107** [mcedit/mcedit2#380]
On the official MCEdit website it says limited support for Minecraft Pocket Edition (aka Bedrock Edition) coming to MCEdit 2.0 but I haven't seen it work in the beta's yet (or maybe at least i'm opening up the world wrong because the world keeps showing up in empty space with nothing there). Is support for MCPE worlds still being worked on, has it been postponed or scrapped entirely until maybe later in the future? There hasn't been a working editor for MCPE worlds for a while now and I know its probably hard to keep it updated because that version frequently updates. It be great if MCEdit supports it sometime in the near future. So I just want to know will it be supported soon. 
Thanks -MetaKnight107

**Comment by codewarrior0** [comment]
MCPE support is not a priority at this time.
