### ISSUE TITLE
Schematic Export and Import

### ISSUE THREAD

**Issue by kalakgl** [mcedit/mcedit2#384]
When I export to schematic and import the same file, then it is not all the blocks.
This is the building I export:
![mcedit_01](https://user-images.githubusercontent.com/12363496/35735561-06cd93b6-0804-11e8-95f4-7634ae41db4a.jpg)
This is the imported:
![mcedit_02](https://user-images.githubusercontent.com/12363496/35735563-06f4c9d6-0804-11e8-8bfd-b8feae35becc.jpg)

What can be wrong here?

**Comment by filipef101** [comment]
use mcedit unified

**Comment by alaskaneagle** [comment]
This is happening to me too.  Found the perfect place in my new world for my old castle and it cut the entire center out of it...  Not the first time I've had this issue.

**Comment by alaskaneagle** [comment]
what are the things codewarrior put here?
