### ISSUE TITLE
unable to find mincraft installation

### ISSUE THREAD

**Issue by martinpritchard** [mcedit/mcedit2#388]
I've just downloaded minecraft windows 10 edition from the windows store, and mcedit is unable to find the installation.  

powershell tells me that the installation is at ```C:\Program Files\WindowsApps\Microsoft.MinecraftUWP_1.2.1002.0_x64__8wekyb3d8bbwe```, but there is no .minecraft folder there and mcedit doesn't seem to like that location when I 'choose a minecraft installation folder'

Does mcedit work with versions downloaded from the windows store in this way?  Any help appreciated.

**Comment by codewarrior0** [comment]
Windows 10 edition is not supported.

**Comment by martinpritchard** [comment]
OK bit confused. On http://www.mcedit.net/ I see the following in the top left corner:

```
Minecraft versions supported:

Java: 1.7, 1.8, 1.9, 1.10, 1.11, Forge 1.7

Bedrock, Windows 10, XBox, PS4, Pocket
```

So on a windows 10 PC, what do I need to do to get mceedit working?

**Comment by codewarrior0** [comment]
Windows 10 edition is not supported.

**Comment by Ozitec** [comment]
Windows 10 is just his just his Operating System he is not saying that he is using Windows 10 edition of minecraft
