### ISSUE TITLE
MCEDIT IMPORT CRASH 1.3

### ISSUE THREAD

**Issue by zxnakzxz** [mcedit/mcedit2#42]
Whenever I try importing a schematics through Mcedit, the system keeps crashing. I need help sorting this out.
nAKZ/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
06/03/2015 19:31:42.862 mcedit[11001]: Cached servers:  []
06/03/2015 19:31:51.280 mcedit[11001]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 19:31:51.280 mcedit[11001]: Traceback (most recent call last):
06/03/2015 19:31:51.281 mcedit[11001]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 19:31:51.281 mcedit[11001]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 19:31:51.281 mcedit[11001]:   File "albow/widget.pyc", line 509, in present
06/03/2015 19:31:51.281 mcedit[11001]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 19:31:51.281 mcedit[11001]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 19:31:51.281 mcedit[11001]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 19:31:51.281 mcedit[11001]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 19:31:51.281 mcedit[11001]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 19:31:51.281 mcedit[11001]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 19:31:51.282 mcedit[11001]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 19:31:51.282 mcedit[11001]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 19:31:51.282 mcedit[11001]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 19:34:03.000 kernel[0]: process mcedit[11001] thread 361189 caught burning CPU!; EXC_RESOURCE supressed due to audio playback
06/03/2015 19:38:22.928 mcedit[11001]: Affected area is too big for this brush mode
06/03/2015 19:39:58.655 Finder[190]: CreateWithFileInfo failed to create URL with FSRef, falling back to blank icon.
06/03/2015 19:42:14.173 mcedit[11001]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 19:42:14.173 mcedit[11001]: Traceback (most recent call last):
06/03/2015 19:42:14.173 mcedit[11001]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 19:42:14.173 mcedit[11001]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/widget.pyc", line 509, in present
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 19:42:14.174 mcedit[11001]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 19:42:14.175 mcedit[11001]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 19:42:14.175 mcedit[11001]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 19:44:51.612 mcedit[11030]: Splash load...
06/03/2015 19:44:53.251 mcedit[11030]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
06/03/2015 19:44:57.263 mcedit[11030]: Minecraft_Server.jar storage initialized.
06/03/2015 19:44:57.263 mcedit[11030]: Each server is stored in a subdirectory of /Users/nAKZ/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
06/03/2015 19:44:57.263 mcedit[11030]: Cached servers:  []
06/03/2015 19:45:06.285 mcedit[11030]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 19:45:06.285 mcedit[11030]: Traceback (most recent call last):
06/03/2015 19:45:06.286 mcedit[11030]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 19:45:06.286 mcedit[11030]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 19:45:06.286 mcedit[11030]:   File "albow/widget.pyc", line 509, in present
06/03/2015 19:45:06.286 mcedit[11030]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 19:45:06.286 mcedit[11030]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 19:45:06.286 mcedit[11030]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 19:45:06.286 mcedit[11030]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 19:45:06.286 mcedit[11030]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 19:45:06.287 mcedit[11030]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 19:45:06.287 mcedit[11030]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 19:45:06.287 mcedit[11030]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 19:45:06.287 mcedit[11030]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 19:45:34.368 Finder[190]: CreateWithFileInfo failed to create URL with FSRef, falling back to blank icon.
06/03/2015 19:46:51.311 mcedit[11030]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 19:46:51.311 mcedit[11030]: Traceback (most recent call last):
06/03/2015 19:46:51.311 mcedit[11030]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 19:46:51.311 mcedit[11030]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/widget.pyc", line 509, in present
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 19:46:51.312 mcedit[11030]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 19:46:51.312 mcedit[11030]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 19:46:51.313 mcedit[11030]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 19:47:00.909 mcedit[11030]: Open File
06/03/2015 19:47:02.695 WindowServer[98]: disable_update_timeout: UI updates were forcibly disabled by application "mcedit" for over 1.00 seconds. Server has re-enabled them.
06/03/2015 19:47:03.423 WindowServer[98]: common_reenable_update: UI updates were finally reenabled by application "mcedit" after 1.73 seconds (server forcibly re-enabled them after 1.00 seconds)
06/03/2015 19:47:04.540 mcedit[11030]: Canceled
06/03/2015 19:47:04.540 mcedit[11030]: No level selected.
06/03/2015 19:47:04.541 mcedit[11030]: [   ERROR][                   root.py:728]:MCEdit version Unified v1.3.0.0 for Minecraft 1.8
06/03/2015 19:47:04.575 mcedit[11030]: Traceback (most recent call last):
06/03/2015 19:47:04.575 mcedit[11030]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 767, in <module>
06/03/2015 19:47:04.575 mcedit[11030]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 726, in main
06/03/2015 19:47:04.575 mcedit[11030]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 560, in main
06/03/2015 19:47:04.575 mcedit[11030]:   File "albow/root.pyc", line 158, in run
06/03/2015 19:47:04.575 mcedit[11030]:   File "albow/root.pyc", line 222, in run_modal
06/03/2015 19:47:04.575 mcedit[11030]:   File "albow/root.pyc", line 560, in gl_clear
06/03/2015 19:47:04.575 mcedit[11030]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/lib/python2.7/OpenGL/error.py", line 232, in glCheckError
06/03/2015 19:47:04.615 mcedit[11030]: GLError: GLError(
06/03/2015 19:47:04.615 mcedit[11030]: err = 1286,
06/03/2015 19:47:04.615 mcedit[11030]: description = 'invalid framebuffer operation',
06/03/2015 19:47:04.615 mcedit[11030]: baseOperation = glClear,
06/03/2015 19:47:04.615 mcedit[11030]: cArguments = (16640,)
06/03/2015 19:47:04.616 mcedit[11030]: )
06/03/2015 19:47:04.616 mcedit[11030]: Traceback (most recent call last):
06/03/2015 19:47:04.616 mcedit[11030]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/__boot__.py", line 399, in <module>
06/03/2015 19:47:04.616 mcedit[11030]: ==================================
06/03/2015 19:47:04.616 mcedit[11030]:  MCEdit has crashed
06/03/2015 19:47:04.616 mcedit[11030]: ==================================
06/03/2015 19:47:04.641 mcedit[11030]:     _run()
06/03/2015 19:47:04.642 mcedit[11030]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/__boot__.py", line 336, in _run
06/03/2015 19:47:04.642 mcedit[11030]:     exec(compile(source, path, 'exec'), globals(), globals())
06/03/2015 19:47:04.642 mcedit[11030]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 776, in <module>
06/03/2015 19:47:04.675 mcedit[11030]:     raw_input("Press the Enter key to close this window")
06/03/2015 19:47:04.675 mcedit[11030]: EOFError: EOF when reading a line
06/03/2015 19:47:04.742 mcedit[11030]: mcedit Error
06/03/2015 19:47:04.742 mcedit[11030]: 2015-03-06 19:47:04.741 mcedit[11030:707] mcedit Error
06/03/2015 19:47:06.808 mcedit[11030]: Press the Enter key to close this window
06/03/2015 19:47:06.860 com.apple.launchd.peruser.501[166]: (org.pythonmac.unspecified.mcedit.66384[11030]) Exited with code: 255
06/03/2015 19:47:11.933 mcedit[11045]: Splash load...
06/03/2015 19:47:12.959 mcedit[11045]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
06/03/2015 19:47:14.406 mcedit[11045]: Minecraft_Server.jar storage initialized.
06/03/2015 19:47:14.406 mcedit[11045]: Each server is stored in a subdirectory of /Users/nAKZ/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
06/03/2015 19:47:14.407 mcedit[11045]: Cached servers:  []
06/03/2015 19:47:21.704 mcedit[11045]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 19:47:21.704 mcedit[11045]: Traceback (most recent call last):
06/03/2015 19:47:21.704 mcedit[11045]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 19:47:21.704 mcedit[11045]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 19:47:21.704 mcedit[11045]:   File "albow/widget.pyc", line 509, in present
06/03/2015 19:47:21.704 mcedit[11045]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 19:47:21.705 mcedit[11045]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 19:47:21.705 mcedit[11045]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 19:47:21.705 mcedit[11045]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 19:47:21.705 mcedit[11045]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 19:47:21.705 mcedit[11045]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 19:47:21.705 mcedit[11045]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 19:47:21.705 mcedit[11045]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 19:47:21.705 mcedit[11045]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 19:47:42.235 mcedit[11045]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 19:47:42.235 mcedit[11045]: Traceback (most recent call last):
06/03/2015 19:47:42.235 mcedit[11045]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 19:47:42.235 mcedit[11045]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 19:47:42.235 mcedit[11045]:   File "albow/widget.pyc", line 509, in present
06/03/2015 19:47:42.235 mcedit[11045]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 19:47:42.236 mcedit[11045]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 19:47:42.236 mcedit[11045]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 19:47:42.236 mcedit[11045]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 19:47:42.236 mcedit[11045]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 19:47:42.236 mcedit[11045]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 19:47:42.236 mcedit[11045]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 19:47:42.236 mcedit[11045]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 19:47:42.236 mcedit[11045]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 19:49:53.417 mcedit[11045]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 19:49:53.417 mcedit[11045]: Traceback (most recent call last):
06/03/2015 19:49:53.417 mcedit[11045]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 19:49:53.418 mcedit[11045]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/widget.pyc", line 509, in present
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 19:49:53.418 mcedit[11045]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 19:49:53.418 mcedit[11045]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 19:49:53.419 mcedit[11045]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 19:52:39.000 kernel[0]: process mcedit[11045] thread 364848 caught burning CPU!; EXC_RESOURCE supressed due to audio playback
06/03/2015 20:01:35.379 mcedit[11045]: Clipping:  _Vector(x=533, y=236, z=489)
06/03/2015 20:02:14.391 Finder[190]: CreateWithFileInfo failed to create URL with FSRef, falling back to blank icon.
06/03/2015 20:02:38.595 mds[39]: (Warning) Server: No stores registered for metascope "kMDQueryScopeNetworkIndexed"
06/03/2015 20:02:52.813 Finder[190]: NSFileCoordinator: Sending of a providerCheckin message was interrupted. Details: Connection interrupted
06/03/2015 20:03:23.097 login[11085]: USER_PROCESS: 11085 ttys000
06/03/2015 20:04:03.000 kernel[0]: Google Chrome He (map: 0xffffff8038a7a4b0) triggered DYLD shared region unnest for map: 0xffffff8038a7a4b0, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:05:07.000 kernel[0]: Google Chrome He (map: 0xffffff803986f4b0) triggered DYLD shared region unnest for map: 0xffffff803986f4b0, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:05:10.000 kernel[0]: Google Chrome He (map: 0xffffff80370a3960) triggered DYLD shared region unnest for map: 0xffffff80370a3960, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:05:10.000 kernel[0]: Google Chrome He (map: 0xffffff8038a7a4b0) triggered DYLD shared region unnest for map: 0xffffff8038a7a4b0, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:05:43.648 apsd[63]: Unrecognized leaf certificate
06/03/2015 20:07:45.694 Finder[190]: NSFileCoordinator: Sending of a providerCheckin message was interrupted. Details: Connection interrupted
06/03/2015 20:07:45.000 kernel[0]: Sandbox: mdworker(11076) deny file-read-xattr /Users/nAKZ/Desktop/world
06/03/2015 20:07:45.000 kernel[0]: Sandbox: mdworker(11147) deny file-read-xattr /Users/nAKZ/Desktop/world
06/03/2015 20:08:52.390 xpcproxy[11153]: assertion failed: 13F34: xpcproxy + 3438 [D559FC96-E6B1-363A-B850-C7AC9734F210]: 0x2
06/03/2015 20:14:43.328 login[11085]: DEAD_PROCESS: 11085 ttys000
06/03/2015 20:15:56.671 login[11202]: USER_PROCESS: 11202 ttys000
06/03/2015 20:16:00.470 WindowServer[98]: disable_update_timeout: UI updates were forcibly disabled by application "TextEdit" for over 1.00 seconds. Server has re-enabled them.
06/03/2015 20:16:02.247 WindowServer[98]: common_reenable_update: UI updates were finally reenabled by application "TextEdit" after 2.78 seconds (server forcibly re-enabled them after 1.00 seconds)
06/03/2015 20:18:29.268 login[11202]: DEAD_PROCESS: 11202 ttys000
06/03/2015 20:18:35.827 Finder[190]: NSFileCoordinator: Sending of a providerCheckin message was interrupted. Details: Connection interrupted
06/03/2015 20:18:35.000 kernel[0]: Sandbox: mdworker(11258) deny file-read-xattr /Users/nAKZ/Downloads/Beta8.3/world copy
06/03/2015 20:18:48.567 mds[39]: (Warning) Server: No stores registered for metascope "kMDQueryScopeNetworkIndexed"
06/03/2015 20:19:03.330 mcedit[11273]: Splash load...
06/03/2015 20:19:05.069 mcedit[11273]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
06/03/2015 20:19:06.000 kernel[0]: Google Chrome He (map: 0xffffff803cc91690) triggered DYLD shared region unnest for map: 0xffffff803cc91690, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:19:07.000 kernel[0]: Google Chrome He (map: 0xffffff803cc915a0) triggered DYLD shared region unnest for map: 0xffffff803cc915a0, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:19:16.444 mcedit[11273]: Minecraft_Server.jar storage initialized.
06/03/2015 20:19:16.445 mcedit[11273]: Each server is stored in a subdirectory of /Users/nAKZ/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
06/03/2015 20:19:16.445 mcedit[11273]: Cached servers:  []
06/03/2015 20:19:37.000 kernel[0]: Google Chrome He (map: 0xffffff803986f4b0) triggered DYLD shared region unnest for map: 0xffffff803986f4b0, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:19:48.000 kernel[0]: Google Chrome He (map: 0xffffff803cc91690) triggered DYLD shared region unnest for map: 0xffffff803cc91690, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:19:57.000 kernel[0]: Google Chrome He (map: 0xffffff80393cbe10) triggered DYLD shared region unnest for map: 0xffffff80393cbe10, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:20:16.000 kernel[0]: Google Chrome He (map: 0xffffff803c72a690) triggered DYLD shared region unnest for map: 0xffffff803c72a690, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:20:19.000 kernel[0]: Google Chrome He (map: 0xffffff803cc91690) triggered DYLD shared region unnest for map: 0xffffff803cc91690, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:20:22.000 kernel[0]: Google Chrome He (map: 0xffffff803986f4b0) triggered DYLD shared region unnest for map: 0xffffff803986f4b0, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:20:28.000 kernel[0]: Google Chrome He (map: 0xffffff80393cbe10) triggered DYLD shared region unnest for map: 0xffffff80393cbe10, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:20:31.000 kernel[0]: Google Chrome He (map: 0xffffff803c72a690) triggered DYLD shared region unnest for map: 0xffffff803c72a690, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:21:47.000 kernel[0]: Google Chrome He (map: 0xffffff80371b2a50) triggered DYLD shared region unnest for map: 0xffffff80371b2a50, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:22:06.000 kernel[0]: Google Chrome He (map: 0xffffff80371b2a50) triggered DYLD shared region unnest for map: 0xffffff80371b2a50, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:22:08.000 kernel[0]: Google Chrome He (map: 0xffffff803c72a690) triggered DYLD shared region unnest for map: 0xffffff803c72a690, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:22:11.000 kernel[0]: Google Chrome He (map: 0xffffff80370a34b0) triggered DYLD shared region unnest for map: 0xffffff80370a34b0, region 0x7fff8a400000->0x7fff8a600000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
06/03/2015 20:22:42.146 mcedit[11298]: Splash load...
06/03/2015 20:22:43.477 mcedit[11298]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
06/03/2015 20:22:46.747 mcedit[11298]: Minecraft_Server.jar storage initialized.
06/03/2015 20:22:46.747 mcedit[11298]: Each server is stored in a subdirectory of /Users/nAKZ/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
06/03/2015 20:22:46.747 mcedit[11298]: Cached servers:  []
06/03/2015 20:23:02.376 mcedit[11298]: [   ERROR][                    root.py:56]:Exception:
06/03/2015 20:23:02.376 mcedit[11298]: Traceback (most recent call last):
06/03/2015 20:23:02.376 mcedit[11298]:   File "mceutils.pyc", line 50, in _alertException
06/03/2015 20:23:02.376 mcedit[11298]:   File "leveleditor.pyc", line 2229, in askLoadWorld
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/widget.pyc", line 509, in present
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/root.pyc", line 261, in run_modal
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/widget.pyc", line 363, in handle_mouse
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/widget.pyc", line 445, in call_handler
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/palette_view.pyc", line 132, in mouse_down
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/grid_view.pyc", line 49, in mouse_down
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/palette_view.pyc", line 159, in click_cell
06/03/2015 20:23:02.377 mcedit[11298]:   File "albow/table_view.pyc", line 161, in click_item
06/03/2015 20:23:02.377 mcedit[11298]:   File "leveleditor.pyc", line 2121, in click_row
06/03/2015 20:23:02.378 mcedit[11298]: AttributeError: 'datetime.datetime' object has no attribute 'dismiss'
06/03/2015 20:23:26.530 mcedit[11298]: Open File
06/03/2015 20:23:30.173 mcedit[11298]: [   ERROR][                   root.py:728]:MCEdit version Unified v1.3.0.0 for Minecraft 1.8
06/03/2015 20:23:30.223 mcedit[11298]: Traceback (most recent call last):
06/03/2015 20:23:30.223 mcedit[11298]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 767, in <module>
06/03/2015 20:23:30.223 mcedit[11298]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 726, in main
06/03/2015 20:23:30.223 mcedit[11298]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 560, in main
06/03/2015 20:23:30.223 mcedit[11298]:   File "albow/root.pyc", line 158, in run
06/03/2015 20:23:30.223 mcedit[11298]:   File "albow/root.pyc", line 222, in run_modal
06/03/2015 20:23:30.223 mcedit[11298]:   File "albow/root.pyc", line 560, in gl_clear
06/03/2015 20:23:30.223 mcedit[11298]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/lib/python2.7/OpenGL/error.py", line 232, in glCheckError
06/03/2015 20:23:30.235 mcedit[11298]: GLError: GLError(
06/03/2015 20:23:30.235 mcedit[11298]: err = 1286,
06/03/2015 20:23:30.235 mcedit[11298]: description = 'invalid framebuffer operation',
06/03/2015 20:23:30.235 mcedit[11298]: baseOperation = glClear,
06/03/2015 20:23:30.235 mcedit[11298]: cArguments = (16640,)
06/03/2015 20:23:30.236 mcedit[11298]: )
06/03/2015 20:23:30.236 mcedit[11298]: Traceback (most recent call last):
06/03/2015 20:23:30.236 mcedit[11298]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/__boot__.py", line 399, in <module>
06/03/2015 20:23:30.236 mcedit[11298]:     _run()
06/03/2015 20:23:30.236 mcedit[11298]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/__boot__.py", line 336, in _run
06/03/2015 20:23:30.236 mcedit[11298]:     exec(compile(source, path, 'exec'), globals(), globals())
06/03/2015 20:23:30.236 mcedit[11298]:   File "/Users/nAKZ/Downloads/mcedit 3.app/Contents/Resources/mcedit.py", line 776, in <module>
06/03/2015 20:23:30.236 mcedit[11298]:     raw_input("Press the Enter key to close this window")
06/03/2015 20:23:30.236 mcedit[11298]: EOFError: EOF when reading a line
06/03/2015 20:23:30.237 mcedit[11298]: ==================================
06/03/2015 20:23:30.237 mcedit[11298]:  MCEdit has crashed
06/03/2015 20:23:30.237 mcedit[11298]: ==================================
06/03/2015 20:23:30.327 mcedit[11298]: mcedit Error
06/03/2015 20:23:30.327 mcedit[11298]: 2015-03-06 20:23:30.326 mcedit[11298:707] mcedit Error
06/03/2015 20:23:31.582 mcedit[11298]: Press the Enter key to close this window
06/03/2015 20:23:31.653 com.apple.launchd.peruser.501[166]: (org.pythonmac.unspecified.mcedit.66384[11298]) Exited with code: 255

**Comment by zxnakzxz** [comment]
![screen shot 2015-03-06 at 20 23 14](https://cloud.githubusercontent.com/assets/11355851/6535852/f58ae7c6-c43f-11e4-87a9-ab4088b3f922.png)
Plus it says this when I log on

**Comment by DragonQuiz** [comment]
Please go to this git https://github.com/Khroki/MCEdit-Unified. This one is for mcedit 2 only thanks

**Comment by zxnakzxz** [comment]
But I'm on Mac I cant run batch files

**Comment by DragonQuiz** [comment]
Copy and paste the error log to pastebin.com as well as the picture over here
https://github.com/Khroki/MCEdit-Unified/issues. This will help alot as there will be a fix soon and will allow contributors to fix the problem since they have no control over this git

**Comment by OniOniOn-** [comment]
You should change repo name to mcedit 2 (NOT MCEDIT 1.x!!!) or something
