### ISSUE TITLE
Error: KeyError(u'Aplha',) ..On loading .schem file-solved

### ISSUE THREAD

**Issue by neekotree** [mcedit/mcedit2#44]
I am getting this error after creating schematics in BetterBOB when trying to load them. I cannot find any reference to the error anywhere on the net. (It SEEMS to be a misspelling of 'alpha')>

anyone else had this?

**Comment by codewarrior0** [comment]
Probably is a misspelling. Open the schematic with NBTExplorer and look for a tag Materials. If its value is "Aplha", you can report the bug to BetterBOB.

**Comment by neekotree** [comment]
Sorted. Many thanks sir. That NBTE is a nifty tool, too.

**Comment by codewarrior0** [comment]
Glad you got it sorted out.
