### ISSUE TITLE
ValueError: badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by samlee946** [mcedit/mcedit2#45]
I encountered this problem when I try to open one of my worlds use mcedit2-2.0.0-alpha1, and other worlds are normal
Here is my save: https://onedrive.live.com/redir?resid=3B414A6FA0C69E1B%21265
It's a multiplayer server, we use Minecraft 1.7.10

**Comment by codewarrior0** [comment]
You have a badly named player file in the playerdata folder. I'll have to make MCEdit ignore those. If you remove the badly named file, it should load.

**Comment by samlee946** [comment]
I removed the backup player file and it work, thanks!
