### ISSUE TITLE
Unable to NBTedit player inventorys in MCEDIT Unified 1.3.0.0

### ISSUE THREAD

**Issue by TheD0ct0r101** [mcedit/mcedit2#46]
So when ever i try to click on the player NBT edit thing called 'Inventory' My MCEDIT just crashes. I am using mods, but even still, MCEDIT allows mods, so it shouldnt crash. FIX?

Please reply to me at scpgovernment@gmail.com

**Comment by codewarrior0** [comment]
Read the [Reporting Guidelines](https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md) and update your issue with the required info.

**Comment by codewarrior0** [comment]
Report MCEdit 1.3.0 issues here: https://github.com/Khroki/MCEdit-Unified/issues
