### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Toni-one** [mcedit/mcedit2#48]
See screenshots. 
![mcedit](https://cloud.githubusercontent.com/assets/10636524/6800034/5382cf90-d21b-11e4-8ee6-883555868864.PNG)
![mcedit2](https://cloud.githubusercontent.com/assets/10636524/6800036/5b640544-d21b-11e4-8270-f6db525ac139.PNG)

**Comment by codewarrior0** [comment]
This might be a problem in PyOpenGL.

Do you know what kind of GPU you have?

**Comment by Toni-one** [comment]
Well... this machine doesn't have any GPU because its a server. I have access to it with a Remotedesktop Connection. :(

**Comment by codewarrior0** [comment]
You can't run MCEdit2 without a GPU, so you're out of luck. Maybe in the future there will be a command-line interface.

MCEdit1 had a command line program called mce.py. I'm not sure if it still works. You can find it here: https://github.com/Khroki/MCEdit-Unified
