### ISSUE TITLE
1.13 / 1.14

### ISSUE THREAD

**Issue by thefabicraft-github** [mcedit/mcedit2#481]
See next comment

**Comment by thefabicraft-github** [comment]
Are you working on an 1.14 and 1.13 support?

**Comment by oliverbooth** [comment]
+

 I would also like to know if it's being worked on.

**Comment by tutosfaciles48** [comment]
This will be very great. For me, I see there are 1 file to add, which correspond to the blocks data

**Comment by thefabicraft-github** [comment]
@tutosfaciles48 Which file? I thought MC added a nee file system in 1.13

**Comment by Septias** [comment]
I would also like to know

**Comment by tutosfaciles48** [comment]
src\mceditlib\blocktypes\minecraft_raw_1_12.json for example

**Comment by spitzi3** [comment]
I cant find a guidelines for contributing link.

**Comment by sbliven** [comment]
Duplicate of #420

**Comment by thefabicraft-github** [comment]
@sbliven Nope, #420 is an duplicate of this thread. Can you please look at the date? Then you´ll see it! ;D

**Comment by thefabicraft-github** [comment]
Yep is an dupllicate of #420
