### ISSUE TITLE
MCEdit wont launch. 

### ISSUE THREAD

**Issue by Gamelesh** [mcedit/mcedit2#49]
![error](https://cloud.githubusercontent.com/assets/11671272/6857749/4c561a0c-d409-11e4-8452-c5d94b2070a5.JPG)

How can I fix it?
Tried many versions of MCEdit but no version works.

**Comment by codewarrior0** [comment]
[MCEdit version? Operating system version?](https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md)

**Comment by codewarrior0** [comment]
`c:\Windows\SysWOW64\` only contains 32-bit DLLs. The only releases of MCEdit 2 are 64-bit only. I don't know why it's trying to load a 32-bit DLL.

**Comment by codewarrior0** [comment]
I have an idea why it is trying to load a 32-bit DLL.

Go to your Environment Variables, edit the PATH variable and if `c:\Windows\SysWOW64\` is in there, remove it.

**Comment by Gamelesh** [comment]
Hmm... I use Windows 7 and MCEdit 2.

And I cant find the PATH variable. There is no PATH variable

**Comment by codewarrior0** [comment]
Then I'm out of ideas.

**Comment by Gamelesh** [comment]
Ok, I found the path and removed the C:\Windows\sysWOW64\. When I start MCEdit it showed me: An error has occured. Unhandled execption: (22, 'Invalid argument')

**Comment by Gamelesh** [comment]
Ok, I tried the MCedit Version 1.3.1.0 and it works. Thank you

**Comment by codewarrior0** [comment]
Huh. That last error means the lastPlayedTime in one of your worlds is before 1970. Guess I've got to check for that.
