### ISSUE TITLE
Problems Editing Entity- Help!

### ISSUE THREAD

**Issue by LilyToon** [mcedit/mcedit2#50]
Hello! So I accidentally spawned an invincible duplicate of my horse inside of my house on Minecraft. I decided I could just edit the Invulnerable:1 to Invulnerable:0 on MCEdit and then just kill it in-game to fix my problem, but editing it isn't working. Whenever I change it to "0" it just switches back to "1". Help?!?!

**Comment by Podshot** [comment]
What version of MCEdit are you using?

**Comment by LilyToon** [comment]
I'm using the 2.0 Tech Demo

**Comment by codewarrior0** [comment]
[MCEdit 2 is currently in pre-alpha. ONLY report issues where MCEdit does not start at all.](https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md)
