### ISSUE TITLE
Unhandled exception: list index out of range

### ISSUE THREAD

**Issue by cameronoz93** [mcedit/mcedit2#51]
Hey there, I am experiencing this issue recently when ever I click 'EDIT' (WorldList)

Error logs: http://gyazo.com/bb64aedff4a2b499958ebf008d95fa62

Any help would be great ;)

**Comment by codewarrior0** [comment]
Can you try it on a newer build and see if it still happens?

https://github.com/mcedit/mcedit2/releases/tag/2.0.0alpha

**Comment by cameronoz93** [comment]
Fixed, thanks :)
