### ISSUE TITLE
Unreadable .jars in versions folder not skipped

### ISSUE THREAD

**Issue by Rho569120** [mcedit/mcedit2#54]
SAys something about a bad zip file?

Exact notification reads:  "An Error has occured.  Unhandled Exception: File is not a zip file"

And the Command Prompt text reads below--

Logging level set
sys.frozen is set
Logging to C:\Users\Robert\DOWNLO~1\MCEDIT~1.0-A\MCEdit User Data\mcedit.log
Setting up console handler
[WARNING][mcedit2.editorapp:77]:UserFilesDirectory: C:\Users\Robert\DOWNLO~1\MCE
DIT~1.0-A\MCEdit User Data
[ERROR][<string>:125]:Unhandled Exception:
        File is not a zip file
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.p
yz\mcedit2.worldlist", line 229, in worldListItemClicked (self is a WorldListWid
get)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.p
yz\mcedit2.util.minecraftinstall", line 74, in getResourceLoader (self is a MCIn
stall)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.p
yz\mcedit2.resourceloader", line 17, in addZipFile (self is a ResourceLoader)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.p
yz\zipfile", line 766, in __init__ (self is a ZipFile)
  File "c:\Users\Rio\Documents\mcedit2-distrib\mcedit2\build\mcedit2\out00-PYZ.p
yz\zipfile", line 807, in _RealGetContents (self is a ZipFile)
BadZipfile: File is not a zip file

**Comment by codewarrior0** [comment]
It's trying to read a minecraft jar from your .minecraft/versions folder and finding something that isn't a zip file. See if you've got anything weird in there and take it out.

**Comment by Rho569120** [comment]
What would qualify as normal, and waht would qualify as weird? So far I have several folders in my versions folder. They are: 1.7.2 , 1.7.2-Forge10.12.0.1047 , 1.7.10, 1.7.10-Forge10.13.0.1180 ,1.7.10-Forge10.13.2.1230, 1.8, 1.8.1

Those are the folders, there are no zip folders in versions.

**Comment by codewarrior0** [comment]
A jar file is a kind of zip file. It might be failing on one of your forge versions, or maybe you actually have a corrupt jar file in there somewhere. I need to make MCEdit skip over those.

You could try pulling everything out except for 1.8, [or you could try one of the newer builds](https://github.com/mcedit/mcedit2/releases/tag/2.0.0alpha).

**Comment by Rho569120** [comment]
I still run with 1.7.2, so MCE2 won't work with it??

**Comment by codewarrior0** [comment]
It still works with 1.7.2. It needs 1.8 to be installed for the textures and block models.

**Comment by Rho569120** [comment]
So, you're the one that made this program, ya?

**Comment by codewarrior0** [comment]
Yes.
