### ISSUE TITLE
dosnt work

### ISSUE THREAD

**Issue by codyfilms** [mcedit/mcedit2#55]
mcedit 2.0.0 dosent let me extract structures fix it plz im about to explode from anger at this stupid download ,besides the fact i just downloaded it and im VERY disappointed in the way you have set the mechanics of the download so PLESE fix the drn thing and make it work!!

**Comment by codewarrior0** [comment]
From the downloads page:

>THIS IS STILL EXPERIMENTAL SOFTWARE AND IS STILL NOT FIT FOR ANY PURPOSE. DO NOT USE FOR ANYTHING.
