### ISSUE TITLE
Crash When Editing A World

### ISSUE THREAD

**Issue by 42iscool42** [mcedit/mcedit2#56]
Here is what the console says: 
[WARNING][editorapp.py:81]:UserFilesDirectory: /usr/MCEdit User Data
Exception AttributeError: "'RevisionHistory' object has no attribute 'nodes'" in  ignored
Could not parse stylesheet of widget 0xdb40a40
Could not parse stylesheet of widget 0xdb45680
Could not parse stylesheet of widget 0xdb4a370
Could not parse stylesheet of widget 0xef10da0
Could not parse stylesheet of widget 0xef15a90
Could not parse stylesheet of widget 0xef1a6b0
Could not parse stylesheet of widget 0xef1f500
Could not parse stylesheet of widget 0xef24140
Could not parse stylesheet of widget 0xef28d70
Could not parse stylesheet of widget 0xef2d7b0
Could not parse stylesheet of widget 0xef324a0
Segmentation fault (core dumped)

If I click edit on a world, it will open up, get to the editing UI, then close with these errors.  Also, I am using Ubuntu.

**Comment by codewarrior0** [comment]
https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md

**Comment by codewarrior0** [comment]
Run the program again with extra verbose mode on, and get me the console output or the `mcedit.log` contents:

`mcedit2 -vv`

**Comment by 42iscool42** [comment]
I had to upload the file to google drive because it was too long for pastebin: https://drive.google.com/file/d/0B1OYagKqY2fQUTIzSWtRaDZGZzQ/view?usp=sharing

**Comment by codewarrior0** [comment]
This happens every time, when you click edit on a world?

Try running `pip install OpenGL_accelerate` to install that module and see if it makes a difference.

**Comment by 42iscool42** [comment]
I installed that and the same thing happens when I try to edit the world.  I tried editing a different world and this is the log: 
[WARNING][editorapp.py:81]:UserFilesDirectory: /usr/MCEdit User Data
Exception AttributeError: "'RevisionHistory' object has no attribute 'nodes'" in  ignored
[ERROR][main.py:129]:Unhandled Exception: 
	
Traceback (most recent call last):
  File "/home/nate/Documents/McEdit/src/mcedit2/editorapp.py", line 607, in editWorldFromList (self is a MCEditApp)
    self.loadFile(filename)
  File "/home/nate/Documents/McEdit/src/mcedit2/editorapp.py", line 572, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, self.worldList.getSelectedIVP(), readonly=readonly, progressCallback=callback)
  File "/home/nate/Documents/McEdit/src/mcedit2/editorsession.py", line 256, in __init__ (self is a EditorSession)
    self.playerPanel = PlayerPanel(self)
  File "/home/nate/Documents/McEdit/src/mcedit2/panels/player.py", line 70, in __init__ (self is a PlayerPanel)
    self.setSelectedPlayerIndex(0)
  File "/home/nate/Documents/McEdit/src/mcedit2/panels/player.py", line 162, in setSelectedPlayerIndex (self is a PlayerPanel)
    self.setSelectedPlayerUUID(UUID)
  File "/home/nate/Documents/McEdit/src/mcedit2/panels/player.py", line 166, in setSelectedPlayerUUID (self is a PlayerPanel)
    self.updateNBTTree()
  File "/home/nate/Documents/McEdit/src/mcedit2/panels/player.py", line 128, in updateNBTTree (self is a PlayerPanel)
    self.nbtEditor.setRootTag(self.selectedPlayer.rootTag if self.selectedPlayer else None)
  File "/home/nate/Documents/McEdit/src/mcedit2/widgets/nbttree/nbteditor.py", line 108, in setRootTag (self is a NBTEditorWidget)
    self.treeView.expandToDepth(0)
OverflowError

**Comment by 42iscool42** [comment]
Here is the verbose crash report for that error: https://docs.google.com/document/d/1dm1L-cMMhOnqIZAM08oAJ-4mrR-sMqm61EZ9FbioctQ/edit?usp=sharing

**Comment by codewarrior0** [comment]
All right. I don't know what's causing this. It will be up to you linux users to figure this one out.

You installed from a git checkout, right? For the record, could you post what commit you're at?

`git rev-parse HEAD`

**Comment by 42iscool42** [comment]
I did not install from git checkout, I just downloaded the source zip from the website and compiled it that way.  I did that yesterday.

**Comment by codewarrior0** [comment]
The source zips are a bit outdated. Would you mind installing from a git checkout and find out if it still crashes?

**Comment by 42iscool42** [comment]
Ok, I installed it from git now.  I got the same error.  Here is the output of git rev-parse HEAD: c487fc7bdf8b99c94f333ba5278011f54d53f9ea

**Comment by OniOniOn-** [comment]
Shouldn't we remove the label?

**Comment by codewarrior0** [comment]
OverflowError should be fixed in 73447bee690abee2b00ba691e10f99c769b2abec on the latest master.
