### ISSUE TITLE
Left clicking = crash

### ISSUE THREAD

**Issue by Craftnime** [mcedit/mcedit2#57]
Minecraft version: 1.8.3
MCedit version: win64 2.0.0 alpha 163
Operatiing system: Windows 7 emulated with Parallels on OS X yosemite
No mods installed.

When I left click on MCedit, the whole Virtual Machine crashed.

Steps:
Download MCedit.
Download mc 1.3.8
open MCedit
open other world
(in my case) choose world from a folder within desktop which was a custom flatlands world set in a forest with decorations on
(screen opens up)
left click the world being shown
CRASH

**Comment by katchyboo** [comment]
i do not know, but maybe david can help.

**Comment by codewarrior0** [comment]
>When I left click on MCedit, the whole Virtual Machine crashed.

This sounds like a bug in Parallels. Try updating the VM software and then update the VM drivers that get installed into the emulated Windows 7.

I recommend installing MCEdit from source instead of using a VM.

Closing as there is nothing I can do on my end.
