### ISSUE TITLE
Linux MCEdit

### ISSUE THREAD

**Issue by DEADLYCOW2** [mcedit/mcedit2#6]
I am a Minecrafter running on the software Linux Mint. I have attempted to install MCEdit and all have gone perfectly, until it said that mcedit.sh was missing. I have no idea what this means, maybe it isn't added by the makers or something, but if not, i need help. Thank you

**Comment by codewarrior0** [comment]
Report issues with MCEdit 1.x here:

https://github.com/Khroki/MCEdit-Unified/issues
