### ISSUE TITLE
help Mcedit problems

### ISSUE THREAD

**Issue by mmeijer363** [mcedit/mcedit2#61]
Help i dont kown wat i most do 
![image](https://cloud.githubusercontent.com/assets/12008237/7215880/1163e472-e5ea-11e4-8cd9-c012254f3a77.png)
![image](https://cloud.githubusercontent.com/assets/12008237/7215881/1171b1c4-e5ea-11e4-90bf-d49668d3d109.png)

**Comment by codewarrior0** [comment]
Install Minecraft 1.8 using the official launcher, or use the next window to add any custom installs you may have.

**Comment by Mabra51** [comment]
I have the same problem, what file/folder do i choose after clicking on the add button?

**Comment by codewarrior0** [comment]
Duplicate of #62
