### ISSUE TITLE
Can't open MCEdit because of log.info() problem

### ISSUE THREAD

**Issue by naor2013** [mcedit/mcedit2#64]
http://pastebin.com/0TNzgr9Q
This is the traceback..
Using Mac OS X 10.10.3, running from source

**Comment by codewarrior0** [comment]
What version of PySide did you install?

**Comment by codewarrior0** [comment]
I'm using PySide 1.2.2 and I can't reproduce this problem. 

I can't make sense of the error message, either. It wants a Qt Metaclass to be registered, but surely the metaclass for Qt's own QModelIndex class is registered!

**Comment by naor2013** [comment]
I was using PySide 1.2.1 but now I updated to 1.2.2 but it still happens
Maybe related to the OS somehow?

**Comment by codewarrior0** [comment]
Try running with `mcedit2 -vv -debug` and then post the log file, which should have a lot more info.

**Comment by codewarrior0** [comment]
My only guess is that it's a problem with the PySide builds you're using. How did you install PySide?

Oh, here's a note from the [PyPI page for installing PySide on OS X](https://pypi.python.org/pypi/PySide#installing-pyside-on-a-mac-os-x-system):

Run this after installing: `pyside_postinstall.py -install`

**Comment by naor2013** [comment]
pyside_postinstall.py -install
Yep, this line fixed the issue
Thanks for the help, please add it to the Getting Started for Mac
