### ISSUE TITLE
Running at 0.1 FPS

### ISSUE THREAD

**Issue by JamMasterz** [mcedit/mcedit2#65]
I just downloaded the newest version of mcedit and loaded up a world ive been playing on in ftb infinity, trying to remove a conflicting block. The problem is that the view is frozen most of the time, running at about 0.1-0.5 fps (numbers in the lower right corner). This makes it pretty much impossible to use the program. Is it a problem with the program, or something on my side?

**Comment by JamMasterz** [comment]
The above is probably because the program was using 4GB of RAM, barely managing to render anything

**Comment by codewarrior0** [comment]
I have no idea. It sounds like it's trying to use the software renderer. All I can do for now is make a couple of changes for a future version: Show an error if it can't get hardware acceleration, and write some info to the log file about the GPU, drivers, and environment in the hopes of learning more.

**Comment by codewarrior0** [comment]
For the record, which version of MCEdit is this?

**Comment by JamMasterz** [comment]
2.0.0 alpha 232

**Comment by codewarrior0** [comment]
All right. You might have to use one of the 1.0 versions to fix your world:

http://khroki.github.io/MCEdit-Unified/

**Comment by tyronx** [comment]
I have very little FPS (2-5) in Alpha 370 especially while moving around. I have a Intel 7i Laptop with 8GB RAM with Intel HD Graphics 4000 - I however also enabled mcedit to use my Geforce GT 630M in the Nvidia Control Panel. Unfortunately I don't see nowhere what graphics card mcedit is really using, like minecrafts F3 Screen does.

Maybe it's because I open a modded world where 99% of blocks are unkown to mcedit?

I'd be happy to help with supplying debug information or testing other versions (latest alpha needs a fix for my reported crash for me to be able to open the modded world).

**Comment by codewarrior0** [comment]
>Maybe adding a small profiler to mcedit would help identify the source of lag?

In the newest builds, go to Options and enable Developer mode. A new Debug menu will appear. From that, select "Profiler". A screenshot of the profiler window might be helpful.

**Comment by codewarrior0** [comment]
>Unfortunately I don't see anywhere what graphics card mcedit is really using, like Minecrafts F3 screen does.

The only place this is shown right now is in the log file, under "Obtained a GL Context".

**Comment by tyronx** [comment]
Using Alpha 450, I enabled developer mode, but I can't see any debug menu: http://i.imgur.com/bJ4LoLW.png

Also mcedit seems to have issues trying to write the log file at all - I can't see the file mcedit claims to log to: http://i.imgur.com/WJkewxY.png
Perhaps I just misread the path because all the folder names are cut off (hehe, that reminds me of the old DOS Times where no file name may be longer than 8 characters)

**Comment by tyronx** [comment]
Ok I also saw logs in the error console, here it doesn seem to find the Intel HD gfx card at least. http://i.imgur.com/mE13gcO.png

I can tinker around a bit more with the nvidia control panel, maybe I can get it to use the geforce card.

**Comment by tyronx** [comment]
In Build 591 I have about double to the FPS (~4-8) now when setting the view distance to 6 and disabling everything but blocks. 

Still very hard to work with and still no debug menu visible.

**Comment by codewarrior0** [comment]
The developer mode was usable before, if you turned it off and then on again.

A recent commit fixed a bug where settings changes weren't announced correctly in a fresh install.

Information from the built-in Profiler is still helpful for FPS issues.

**Comment by Sounas-mc** [comment]
Hello,

i grant that this is a later version of MCedit 2 but i'm having the same issue as described  a few months ago. At first, when i load a world, everything seems fine. It is the moment that i edit the world, in any way (even a size 1 ball), that the FPS drops to 2-3. I don't have a beast of a computer, but neither an extremely oudated one, and i close most other applications before going into MCedit.

I attached a screenie of the built-in Profiler. Much obliged if you could shed some light on this :)

- Sounas
![profilersounas](https://cloud.githubusercontent.com/assets/15659679/10951358/68b759f2-833d-11e5-9a33-b8e36e2f33f4.png)

**Comment by codewarrior0** [comment]
@Sounas-mc What are your system specs? If you go to Debug -> Raise Error, you'll get a dialog with some of your specs in it.

If you're running inside a VirtualBox VM, did you remember to enable 3D acceleration in the display settings?

**Comment by Sounas-mc** [comment]
Here you go

![sounasinfo](https://cloud.githubusercontent.com/assets/15659679/10955421/f7f25732-8353-11e5-8429-2480d71059ed.png)

**Comment by codewarrior0** [comment]
Is the "Intel Graphics" part correct? Or do you use a discrete ATI or NVidia graphics card?

**Comment by Sounas-mc** [comment]
I believe it's an integrated video card, yeah.

**Comment by codewarrior0** [comment]
No news or duplicate reports in half a year.
