### ISSUE TITLE
ERROR: Unhandled exeption: Pre-Anvil Versions are not supported (for now)

### ISSUE THREAD

**Issue by MrLetsplay2003** [mcedit/mcedit2#66]
Please post, what the ERROR has to say and what i shell do. :D

**Comment by codewarrior0** [comment]
Play the world in a recent version of Minecraft to convert it.

Supporting ancient worlds from the Minecraft Beta days is not a priority right now.

**Comment by MrLetsplay2003** [comment]
Ok, i will test this

**Comment by MrLetsplay2003** [comment]
This doesn't work, MCEdit doesn't start D:

**Comment by MrLetsplay2003** [comment]
Or....

**Comment by MrLetsplay2003** [comment]
YAY IT WORKS, THANKS :DDDD
