### ISSUE TITLE
Mac world list looks weird

### ISSUE THREAD

**Issue by naor2013** [mcedit/mcedit2#67]
http://puu.sh/hkWx5.png
The world list on a Mac is kind of weird..
Running from source

**Comment by codewarrior0** [comment]
Must be this Qt bug: https://bugreports.qt.io/browse/QTBUG-40833

How does the rest of the app look?

**Comment by naor2013** [comment]
It doesn't seem like they talk about lists in the bug report so I'm not sure it's that..
What do you mean by the rest of the app?
Wouldn't it be better to use PyQt 5 which updates often and not PySide which didn't update for 11 months? Would the conversation between the 2 be hard or is it similar?

**Comment by codewarrior0** [comment]
I haven't had any problems with PySide so far. If anyone wants to try porting MCEdit to PyQt, you're more than welcome.

**Comment by codewarrior0** [comment]
No news in over a year.
