### ISSUE TITLE
Running from source required changes.

### ISSUE THREAD

**Issue by Rubisk** [mcedit/mcedit2#7]
It took me a while to get it runnning from source. main.py had to be placed in mcedit2\src, instead of mcedit2\src\mcedit2. I had to change 1 import for that in load_ui, fixing about 80 other imports. nbt and nbt_util had to be copied from the old mcedit into mceditlib.

        GL.glTexImage2D(GL.GL_PROXY_TEXTURE_2D, 0, GL.GL_RGBA, size, size, 0, GL.GL_RGBA, GL.GL_UNSIGNED_BYTE, 0)
        maxsize = GL.glGetTexLevelParameteriv(GL.GL_PROXY_TEXTURE_2D, 0, GL.GL_TEXTURE_WIDTH)

these lines also caused an error. I commented them out and changed it to maxsize = 16384, which seems to work fine. Don't know whether or not this has to do with me missing libraries or an error in the code.

**Comment by codewarrior0** [comment]
What if you launch using `PYTHONPATH=src python src/mcedit2/main.py`?

Also, you're fired for saying "an error" without posting the error.

**Comment by codewarrior0** [comment]
Oh, that's right, you need to build `nbt.pyd`. The quick way is to run `python setup.py --build-ext --inplace`. setup.py was broken for a bit, I just pushed a fix.

The long way is to setup a virtual env, blah blah blah, run `python setup.py develop`, work out any bugs in the script install, then run `mcedit2`

**Comment by Rubisk** [comment]
Whoops forgot to share the log, here: http://pastebin.com/cuC0SuR9

Got it running a bit more legit now. Am able to at least run main.py in a proper way. With the copied nbt.py file I still run into the GL error. Without it, it doesn't work (of course). 

python setup.py build_ext --inplace throws the following error:
http://pastebin.com/Cvwn5rVD

**Comment by codewarrior0** [comment]
That's odd. That last parameter is meant to be a null pointer, not a pointer to a one-byte array. But PyOpenGL interprets it as a byte value instead. Maybe `ctypes.c_voidp(0)`?

Anyway, I'll write a getting-started thing for developers as soon as I'm done with the block model loader.
