### ISSUE TITLE
Crash when opening a new world

### ISSUE THREAD

**Issue by Fak3r68** [mcedit/mcedit2#71]
![mcedit bug](https://cloud.githubusercontent.com/assets/10348953/7387021/fcb0e444-ee59-11e4-8fbf-dd50c3c77a6f.PNG)

Help me please !!

**Comment by codewarrior0** [comment]
[Please review the guidelines for contributing to this repository.](https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md)
