### ISSUE TITLE
Array casting error in updateHeightmap

### ISSUE THREAD

**Issue by xIRAQx** [mcedit/mcedit2#74]
This problem is when i just click to brush, on my 32 bit
![err](https://cloud.githubusercontent.com/assets/12281415/7502664/faead8ec-f43d-11e4-855c-0b92665af39f.PNG)

**Comment by codewarrior0** [comment]
As a workaround, go to the "Options" menu and uncheck "Enable Lighting Updates".

The lighting update code still needs a lot of work.

**Comment by codewarrior0** [comment]
The lighting update was completely rewritten. This issue cannot be relevant any more.
