### ISSUE TITLE
Cannot download MCEdit 2.0 for Mac 

### ISSUE THREAD

**Issue by DroidPvPMaster** [mcedit/mcedit2#75]
Please help me
I tried to download MCEdit 2.0 but I got 1.3.2

**Comment by DroidPvPMaster** [comment]
![screen shot 2015-05-06 at 10 22 58 pm](https://cloud.githubusercontent.com/assets/12286078/7507495/817f70f2-f43e-11e4-912b-580507176f44.png)

Also I have this too

**Comment by DroidPvPMaster** [comment]
There is a dinosaur

**Comment by codewarrior0** [comment]
MCEdit 2 isn't available for Mac yet. You'll have to use 1.3 until then.
