### ISSUE TITLE
Hard shadows

### ISSUE THREAD

**Issue by cbprog** [mcedit/mcedit2#76]
Did you know that when import objects from my library, for example from 1.6.4. to 1.8 objects appear black?  Is there a way to transfer the construction of the new version?
![GitHub Logo] (http://www.cb.16mb.com/temp/black_shadows.jpg)

**Comment by codewarrior0** [comment]
That's because the lighting update in MCEdit is still incomplete. If you go into the building in Minecraft it will start to update the lighting.

**Comment by cbprog** [comment]
Please look at this and say, this is a problem spigot while the save world or is a problem at the wrong MсEdit data transfer? 
Look to the end. Several times I specifically restart the server.
http://www.youtube.com/watch?v=nbHbgP1IAT0
p.s. Sorry for the lag was running 2 servers
