### ISSUE TITLE
Can't open MCEdit

### ISSUE THREAD

**Issue by Threndrik** [mcedit/mcedit2#77]
I'm using version 2.0.0alpha-232, and I get this whenever I open it: MCEdit requires an installed Minecraft version 1.8 or greater to access block textures, models, and metadata.
Yes, I have Minecraft 1.8 installed. Also, I'm using windows 32 bit version.
Help anyone?

**Comment by codewarrior0** [comment]
Did you try adding the Minecraft installation in the next window?

**Comment by Threndrik** [comment]
Yeah, I'm not sure if I'm doing it right, but I go to the .minecraft
folder, and then to the versions folder, and from there I have selected all
the 1.8 versions and 1.7.10. So Maybe I'm doing it wrong. I don't know.

**Comment by Threndrik** [comment]
Okay, now it says An error has occurred. Unhandled exception: Pre-Anvil
world formats are not supported (for now)

**Comment by Rubisk** [comment]
Try remove any pre-anvil world from your save folder?

**Comment by Threndrik** [comment]
Okay, but now it says 'MCEditApp' object has no attribute 'worldList'.

**Comment by codewarrior0** [comment]
That should be fixed in build 309.

**Comment by Threndrik** [comment]
Okay, thanks.
