### ISSUE TITLE
AttributeError: 'PySide.QtGui.QComboBox' object has no attribute 'textChanged'

### ISSUE THREAD

**Issue by naor2013** [mcedit/mcedit2#84]
File "/Users/naor/mcedit2/src/mcedit2/widgets/inventory.py", line 272, in __init__ (self is a InventoryEditor)
    self.itemListSearchBox.textChanged.connect(self.searchTextChanged)
AttributeError: 'PySide.QtGui.QComboBox' object has no attribute 'textChanged'

Using Mac from source, didn't send the all traceback because I think it will be enough but if you need more info, just tell me.
When commenting this line, there's no error related that occurs

**Comment by codewarrior0** [comment]
Oddly, that line works for me and the problem doesn't happen in the released builds. The `textChanged` signal was renamed to `editTextChanged` in Qt 4 but apparently there is some kind of compatibility in place, at least in my version. 

I'm using PySide 1.2.2. What version do you have?

**Comment by naor2013** [comment]
Yep, it's fixed..
Sorry for not answering quickly, I have PySide 1.2.1 btw
How can I update it to 1.2.2? When I uninstall and install it again with "pip install", it installs 1.2.1

**Comment by codewarrior0** [comment]
`pip install -U pyside` upgrades to the latest version. `pip install pyside==1.2.2` specifies a version to install.
