### ISSUE TITLE
MCEdit2 Schematic Error: 'itertools.chain' object has no attribute 'isCompound'

### ISSUE THREAD

**Issue by Raftyyy** [mcedit/mcedit2#89]
Hi, everytime i try to use a schematic my mcedit crashes..
![mcedit2crash](https://cloud.githubusercontent.com/assets/12443395/7630074/d823a032-fa32-11e4-8573-fbffbf549195.PNG)

**Comment by codewarrior0** [comment]
You need to post your MCEdit version and `mcedit.log` file.

**Comment by codewarrior0** [comment]
Never mind.
