### ISSUE TITLE
Area size

### ISSUE THREAD

**Issue by Gageb** [mcedit/mcedit2#9]
When using MCedit and trying to select a large area the selection tool will go of my screen so i cant select the area.

**Comment by codewarrior0** [comment]
When reporting an issue about MCEdit, you _must_ include the following or your report will not be helpful:

* **Steps to Reproduce** - Step by step, tell us exactly which buttons to click on, text to enter, and keys to press that lead you to discover the problem.
* **MCEdit Version Number** - Found in the title bar of the main window.
* **Minecraft Version Number** - You should already know how to find this. Also include a list of the mods you are using.
* **Operating System Version** - At the very least, say whether you are on Windows, Mac, or Linux. To get a more exact version (e.g. "Windows Vista SP1 64-bit", "Mac OS X 10.6.4"):
 + Windows: click Start, then right-click Computer and choose "Properties". 
 + Mac OS X: Choose "About This Mac" from the Apple menu.  
 + Linux: See your distro's documentation to find out how to get the version number.
 + An animal is not a version number.<br><br>

**Comment by IntensePlatypus** [comment]
Schematics will save but when I try to open them up with McEdit the program crashes.
MCEdit v1.2.4.0
1.8.1 
Mac Version 10.9.5
