### ISSUE TITLE
Blocks do not render at all. [worldscene.py:146]:Rendering chunk (x, y) failed: TypeError('__init__( ) takes at least 3 arguments (2 given)',)

### ISSUE THREAD

**Issue by Rubisk** [mcedit/mcedit2#90]
Console gets spammed with this, until my pc gets so laggy that mcedit just terminates:
http://pastebin.com/kjGSSB5u

I would fix it myself, but can't make much sense of the error report. It might be because it's the cython file, but I don't think that's the line with calling the __init__ method.

**Comment by codewarrior0** [comment]
Cython file was changed. You need to `setup.py develop` or `setup.py build_ext --inplace`

**Comment by Rubisk** [comment]
Whoops, thanks.
