### ISSUE TITLE
MCEdit Error: Permission Denied (Or) OIError

### ISSUE THREAD

**Issue by GeorgioMC** [mcedit/mcedit2#93]
I have this problem. The mcedit jump this error why i paste a copy in the world, or save, fill, etc.

Sorry for my english, i speak spanish.

Help!.

**Comment by Rubisk** [comment]
Please provide a proper traceback and a better way to reproduce the issue. For more information, look here: https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md
