### ISSUE TITLE
Error 0x0000000000000000 ver.370 x64

### ISSUE THREAD

**Issue by cbprog** [mcedit/mcedit2#95]
![GitHub Logo](http://www.cb.16mb.com/temp/mcedit.jpg)

**Comment by Rubisk** [comment]
duplicate of #78?

**Comment by codewarrior0** [comment]
Yes.

**Comment by OniOniOn-** [comment]
If my pc run mcedit 2 tech. preview long time ago, would it not get this error? Or is it just a real problem in code.
