### ISSUE TITLE
MCEdit Import error

### ISSUE THREAD

**Issue by JonnoPenguin** [mcedit/mcedit2#98]
Every time I try to import a schematic is simply says that the Ray has exceeded max distance. Why and can I stop this?

**Comment by Rubisk** [comment]
Please read this first: https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md

**Comment by LoveKitten** [comment]
When I downloaded MCEdit , I tried to import my Minecraft Installation but it said me my Minecraft is has to be 1.8 version or greater but my MC is in 1.8 version , why?
(sorry I don't speaking English)
