### ISSUE TITLE
MCEdit Error

### ISSUE THREAD

**Issue by LoveKitten** [mcedit/mcedit2#99]
When I downloaded MCEdit , I tried to import my Minecraft Installation but it said me my Minecraft is has to be 1.8 version or greater but my MC is in 1.8 version , why?
(sorry I don't speaking English)

**Comment by LoveKitten** [comment]
plz answer it

**Comment by LoveKitten** [comment]
![mcedit](https://cloud.githubusercontent.com/assets/12571253/7783368/177c7002-0149-11e5-9797-93d0ce9e56a3.png)

**Comment by codewarrior0** [comment]
Can you post your MCEdit version, and your `mcedit.log` file that's in the MCEdit User Data folder?

**Comment by RafiArsanta** [comment]
If i open The mcedit after Setting up Console handler
it say "The Procedure entry point ConvertLengthToIpv4Maxk Could not be located in the dynamic link library IPHLPAPI.DLL"

and How i must To Do? Plss
